-- ============================================================
-- 彼岸花仙境 / RO_WEB V0.9.86A
-- 低流量延遲聊天：世界聊天 + 私信 + 封鎖 + 未來公告/組隊/公會預留
--
-- 設計重點：
-- 1. 不使用 Supabase Realtime / WebSocket。
-- 2. 客戶端只用 message_id 增量輪詢，不重抓完整聊天室。
-- 3. 世界聊天保留 48 小時；私信保留 7 天（於發言時順手清理）。
-- 4. 玩家資訊使用訊息送出當下角色快照，不為每行聊天額外查玩家資料。
-- 5. 所有寫入/讀取皆走 SECURITY DEFINER RPC，不開放資料表直接寫入。
-- ============================================================

create table if not exists public.ro_chat_messages (
  message_id bigint generated by default as identity primary key,
  message_type text not null default 'world',
  sender_account_id uuid not null references public.ro_accounts(account_id) on delete cascade,
  sender_player_id bigint not null,
  sender_character_id uuid null references public.ro_characters(character_id) on delete set null,
  sender_name text not null,
  sender_base_level integer not null default 1,
  sender_job_name text not null default '初學者',
  recipient_account_id uuid null references public.ro_accounts(account_id) on delete cascade,
  recipient_player_id bigint null,
  body text not null,
  created_at timestamptz not null default now(),
  constraint ro_chat_type_check check (message_type in ('world','whisper','announcement','party','guild')),
  constraint ro_chat_body_len check (char_length(body) between 1 and 120),
  constraint ro_chat_sender_name_len check (char_length(sender_name) between 1 and 24)
);

create index if not exists ro_chat_messages_created_idx
  on public.ro_chat_messages(created_at desc);
create index if not exists ro_chat_messages_type_id_idx
  on public.ro_chat_messages(message_type, message_id desc);
create index if not exists ro_chat_messages_recipient_idx
  on public.ro_chat_messages(recipient_account_id, message_id desc)
  where recipient_account_id is not null;
create index if not exists ro_chat_messages_sender_idx
  on public.ro_chat_messages(sender_account_id, message_id desc);

create table if not exists public.ro_chat_blocks (
  blocker_account_id uuid not null references public.ro_accounts(account_id) on delete cascade,
  blocked_account_id uuid not null references public.ro_accounts(account_id) on delete cascade,
  blocked_player_id bigint not null,
  created_at timestamptz not null default now(),
  primary key (blocker_account_id, blocked_account_id),
  constraint ro_chat_no_self_block check (blocker_account_id <> blocked_account_id)
);

create index if not exists ro_chat_blocks_player_idx
  on public.ro_chat_blocks(blocker_account_id, blocked_player_id);

alter table public.ro_chat_messages enable row level security;
alter table public.ro_chat_blocks enable row level security;

revoke all on public.ro_chat_messages from anon, authenticated;
revoke all on public.ro_chat_blocks from anon, authenticated;

create or replace function public.ro_chat_assert_account(p_account_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'RO_AUTH_REQUIRED';
  end if;
  if not exists (
    select 1 from public.ro_accounts a
     where a.account_id = p_account_id
       and a.user_id = auth.uid()
       and coalesce(a.account_status,'active') = 'active'
  ) then
    raise exception 'RO_CHAT_ACCOUNT_PERMISSION_DENIED';
  end if;
  return p_account_id;
end;
$$;

create or replace function public.ro_chat_send(
  p_account_id uuid,
  p_character_id uuid,
  p_message_type text,
  p_body text,
  p_target_player_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_type text := lower(btrim(coalesce(p_message_type,'')));
  v_body text := btrim(regexp_replace(coalesce(p_body,''), '[\r\n\t]+', ' ', 'g'));
  v_sender_player_id bigint;
  v_sender_name text;
  v_sender_base integer;
  v_sender_job text;
  v_target_account_id uuid;
  v_target_player_id bigint;
  v_result jsonb;
  v_cooldown interval;
begin
  perform public.ro_chat_assert_account(p_account_id);

  if v_type not in ('world','whisper') then
    raise exception 'RO_CHAT_UNSUPPORTED_MESSAGE_TYPE';
  end if;
  if char_length(v_body) < 1 then
    raise exception 'RO_CHAT_EMPTY_MESSAGE';
  end if;
  if char_length(v_body) > 120 then
    raise exception 'RO_CHAT_MESSAGE_TOO_LONG';
  end if;

  select a.player_id, c.name, greatest(1,coalesce(c.base_level,1)), coalesce(nullif(c.job_name,''),'初學者')
    into v_sender_player_id, v_sender_name, v_sender_base, v_sender_job
    from public.ro_accounts a
    join public.ro_characters c on c.account_id = a.account_id
   where a.account_id = p_account_id
     and a.user_id = auth.uid()
     and c.character_id = p_character_id
     and coalesce(a.account_status,'active') = 'active';

  if v_sender_player_id is null or v_sender_name is null then
    raise exception 'RO_CHAT_CHARACTER_PERMISSION_DENIED';
  end if;

  v_cooldown := case when v_type = 'world' then interval '3 seconds' else interval '2 seconds' end;
  if exists (
    select 1 from public.ro_chat_messages m
     where m.sender_account_id = p_account_id
       and m.created_at > now() - v_cooldown
  ) then
    raise exception 'RO_CHAT_RATE_LIMIT';
  end if;

  if v_type = 'whisper' then
    if p_target_player_id is null or p_target_player_id <= 0 then
      raise exception 'RO_CHAT_TARGET_REQUIRED';
    end if;
    if p_target_player_id = v_sender_player_id then
      raise exception 'RO_CHAT_CANNOT_WHISPER_SELF';
    end if;

    select a.account_id, a.player_id
      into v_target_account_id, v_target_player_id
      from public.ro_accounts a
     where a.player_id = p_target_player_id
       and coalesce(a.account_status,'active') = 'active'
     limit 1;

    if v_target_account_id is null then
      raise exception 'RO_CHAT_TARGET_NOT_FOUND';
    end if;

    if exists (
      select 1 from public.ro_chat_blocks b
       where b.blocker_account_id = v_target_account_id
         and b.blocked_account_id = p_account_id
    ) then
      raise exception 'RO_CHAT_WHISPER_BLOCKED';
    end if;
    if exists (
      select 1 from public.ro_chat_blocks b
       where b.blocker_account_id = p_account_id
         and b.blocked_account_id = v_target_account_id
    ) then
      raise exception 'RO_CHAT_TARGET_BLOCKED_BY_YOU';
    end if;
  end if;

  -- 不靠排程器：有人發言時順手清理過期訊息，避免資料表無限制成長。
  delete from public.ro_chat_messages
   where (message_type in ('world','announcement') and created_at < now() - interval '48 hours')
      or (message_type = 'whisper' and created_at < now() - interval '7 days');

  insert into public.ro_chat_messages (
    message_type,
    sender_account_id, sender_player_id, sender_character_id,
    sender_name, sender_base_level, sender_job_name,
    recipient_account_id, recipient_player_id,
    body
  ) values (
    v_type,
    p_account_id, v_sender_player_id, p_character_id,
    left(v_sender_name,24), v_sender_base, left(v_sender_job,80),
    case when v_type='whisper' then v_target_account_id else null end,
    case when v_type='whisper' then v_target_player_id else null end,
    v_body
  )
  returning jsonb_build_object(
    'message_id', message_id,
    'message_type', message_type,
    'sender_player_id', sender_player_id,
    'sender_character_id', sender_character_id,
    'sender_name', sender_name,
    'sender_base_level', sender_base_level,
    'sender_job_name', sender_job_name,
    'recipient_player_id', recipient_player_id,
    'body', body,
    'created_at', created_at
  ) into v_result;

  return v_result;
end;
$$;

create or replace function public.ro_chat_poll(
  p_account_id uuid,
  p_after_id bigint default 0,
  p_limit integer default 20
)
returns table (
  message_id bigint,
  message_type text,
  sender_player_id bigint,
  sender_character_id uuid,
  sender_name text,
  sender_base_level integer,
  sender_job_name text,
  recipient_player_id bigint,
  body text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_limit integer := greatest(1, least(coalesce(p_limit,20), 30));
begin
  perform public.ro_chat_assert_account(p_account_id);

  if coalesce(p_after_id,0) <= 0 then
    return query
    with visible as (
      select m.message_id,m.message_type,m.sender_player_id,m.sender_character_id,m.sender_name,
             m.sender_base_level,m.sender_job_name,m.recipient_player_id,m.body,m.created_at
        from public.ro_chat_messages m
       where (
          (m.message_type in ('world','announcement') and m.created_at >= now() - interval '48 hours')
          or
          (m.message_type = 'whisper'
             and m.created_at >= now() - interval '7 days'
             and (m.sender_account_id = p_account_id or m.recipient_account_id = p_account_id))
       )
       and not exists (
         select 1 from public.ro_chat_blocks b
          where b.blocker_account_id = p_account_id
            and b.blocked_account_id = m.sender_account_id
       )
       order by m.message_id desc
       limit v_limit
    )
    select v.message_id,v.message_type,v.sender_player_id,v.sender_character_id,v.sender_name,
           v.sender_base_level,v.sender_job_name,v.recipient_player_id,v.body,v.created_at
      from visible v
     order by v.message_id asc;
  else
    return query
    select m.message_id,m.message_type,m.sender_player_id,m.sender_character_id,m.sender_name,
           m.sender_base_level,m.sender_job_name,m.recipient_player_id,m.body,m.created_at
      from public.ro_chat_messages m
     where m.message_id > p_after_id
       and (
          (m.message_type in ('world','announcement') and m.created_at >= now() - interval '48 hours')
          or
          (m.message_type = 'whisper'
             and m.created_at >= now() - interval '7 days'
             and (m.sender_account_id = p_account_id or m.recipient_account_id = p_account_id))
       )
       and not exists (
         select 1 from public.ro_chat_blocks b
          where b.blocker_account_id = p_account_id
            and b.blocked_account_id = m.sender_account_id
       )
     order by m.message_id asc
     limit v_limit;
  end if;
end;
$$;

create or replace function public.ro_chat_is_blocked(
  p_account_id uuid,
  p_target_player_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.ro_chat_assert_account(p_account_id);
  return exists (
    select 1
      from public.ro_chat_blocks b
     where b.blocker_account_id = p_account_id
       and b.blocked_player_id = p_target_player_id
  );
end;
$$;

create or replace function public.ro_chat_set_block(
  p_account_id uuid,
  p_target_player_id bigint,
  p_block boolean default true
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_target_account_id uuid;
  v_self_player_id bigint;
begin
  perform public.ro_chat_assert_account(p_account_id);
  select player_id into v_self_player_id from public.ro_accounts where account_id = p_account_id;
  if p_target_player_id is null or p_target_player_id <= 0 or p_target_player_id = v_self_player_id then
    raise exception 'RO_CHAT_INVALID_BLOCK_TARGET';
  end if;

  select account_id into v_target_account_id
    from public.ro_accounts
   where player_id = p_target_player_id
     and coalesce(account_status,'active') = 'active'
   limit 1;
  if v_target_account_id is null then raise exception 'RO_CHAT_TARGET_NOT_FOUND'; end if;

  if coalesce(p_block,true) then
    insert into public.ro_chat_blocks(blocker_account_id,blocked_account_id,blocked_player_id)
    values(p_account_id,v_target_account_id,p_target_player_id)
    on conflict (blocker_account_id,blocked_account_id)
    do update set blocked_player_id=excluded.blocked_player_id, created_at=now();
    return true;
  else
    delete from public.ro_chat_blocks
     where blocker_account_id=p_account_id and blocked_account_id=v_target_account_id;
    return false;
  end if;
end;
$$;

revoke all on function public.ro_chat_assert_account(uuid) from public;
revoke all on function public.ro_chat_send(uuid,uuid,text,text,bigint) from public;
revoke all on function public.ro_chat_poll(uuid,bigint,integer) from public;
revoke all on function public.ro_chat_is_blocked(uuid,bigint) from public;
revoke all on function public.ro_chat_set_block(uuid,bigint,boolean) from public;

grant execute on function public.ro_chat_send(uuid,uuid,text,text,bigint) to authenticated;
grant execute on function public.ro_chat_poll(uuid,bigint,integer) to authenticated;
grant execute on function public.ro_chat_is_blocked(uuid,bigint) to authenticated;
grant execute on function public.ro_chat_set_block(uuid,bigint,boolean) to authenticated;

comment on table public.ro_chat_messages is 'RO_WEB V0.9.86A low-traffic incremental chat messages.';
comment on function public.ro_chat_poll(uuid,bigint,integer) is 'Incremental player-visible chat polling. No Realtime/WebSocket required.';
