//=======================================
// RO_WEB Enchant Material Exchange Runtime v0.9.82HL
// Formal EP19 recipes. Always browse all recipes; never filters by inventory.
//=======================================
(function(){
  "use strict";
  const VERSION="0.9.82HL",DATA_KEY="data/enchant_material_exchange.json";
  const state={groupId:"all",search:"",selectedRecipeId:null,quantity:1};
  function byId(id){return document.getElementById(id);}
  function n(v,f=0){const x=Number(v);return Number.isFinite(x)?x:f;}
  function escapeHtml(value){return String(value??"").replace(/[&<>'"]/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[ch]);}
  function iconPath(id){return `images/items/${Number(id)}.webp?v=${VERSION}`;}
  function data(){return window.RO_WEB_DATA?.[DATA_KEY]||null;}
  function recipes(){return Array.isArray(data()?.recipes)?data().recipes:[];}
  function itemMap(){return new Map((data()?.catalog||[]).map(row=>[Number(row.id),row]));}
  function recipeMap(){return new Map(recipes().map(row=>[String(row.id),row]));}
  function selectedRecipe(){return recipeMap().get(String(state.selectedRecipeId))||null;}
  function item(id){return itemMap().get(Number(id))||window.getItemData?.(id)||{id:Number(id),name:`物品 ${id}`,description:""};}
  function inventoryCount(id){return (window.player?.inventory||[]).reduce((sum,row)=>String(row?.id)===String(id)&&!row?.instanceId?sum+Math.max(0,n(row.count)):sum,0);}
  function maxBatch(){return Math.max(1,n(data()?.policy?.maxBatch,999999));}
  function clampQuantity(value){return Math.max(1,Math.min(maxBatch(),Math.floor(n(value,1))));}
  function isOpen(){const host=byId("enchantMaterialExchangeWindow");return !!host&&!host.hidden&&!host.classList.contains("hidden-window");}
  function group(){return (data()?.groups||[]).find(row=>row.id===state.groupId)||(data()?.groups||[])[0]||null;}
  function visibleRecipes(){const allowed=new Set((group()?.recipeIds||recipes().map(x=>x.id)).map(String));return recipes().filter(row=>allowed.has(String(row.id))).filter(row=>{if(!state.search)return true;const output=item(row.output?.id);const inputs=(row.inputs||[]).map(x=>item(x.id)?.name).join(" ");return `${row.name||""} ${row.id||""} ${output?.name||""} ${output?.id||""} ${inputs}`.toLowerCase().includes(state.search);});}
  function materialsEnough(recipe,quantity=state.quantity){return (recipe?.inputs||[]).every(row=>inventoryCount(row.id)>=n(row.amount)*quantity)&&n(window.player?.zeny)>=n(recipe?.zeny)*quantity;}
  function snapshot(){return JSON.parse(JSON.stringify({inventory:window.player?.inventory||[],zeny:n(window.player?.zeny)}));}
  function restore(snap){window.player.inventory=snap.inventory;window.player.zeny=snap.zeny;}
  function consume(id,amount){let need=amount;for(let i=(window.player?.inventory||[]).length-1;i>=0&&need>0;i--){const row=window.player.inventory[i];if(row?.instanceId||String(row?.id)!==String(id))continue;const take=Math.min(need,Math.max(0,n(row.count)));row.count=n(row.count)-take;need-=take;if(row.count<=0)window.player.inventory.splice(i,1);}if(need>0)throw new Error(`材料不足：${item(id).name}`);}
  function grant(id,amount){const current=(window.player?.inventory||[]).find(row=>!row?.instanceId&&String(row?.id)===String(id));if(current)current.count=n(current.count)+amount;else window.player.inventory.push({id:Number(id),name:item(id).name,count:amount,locked:false});}
  function setMessage(text){const el=document.querySelector("#enchantMaterialExchangeWindow .enchant-exchange-message");if(el)el.textContent=String(text||"");}

  function openEnchantMaterialExchange(npc){const host=byId("enchantMaterialExchangeWindow");if(!host||!data())return false;state.groupId="all";state.search="";state.quantity=1;state.selectedRecipeId=recipes()[0]?.id||null;const name=byId("enchantExchangeNpcName"),search=byId("enchantExchangeSearch");if(name)name.textContent=npc?.name||"綜合材料兌換研究員";if(search)search.value="";host.hidden=false;host.classList.remove("hidden-window");renderAll();setMessage("可在此查看全部黯淡冰晶材料配方；選擇配方與數量，備妥需求後即可兌換。" );window.bringWindowToFront?.(host);window.addBattleLog?.(`${npc?.name||"綜合材料兌換研究員"}：材料兌換服務已開啟。`);return true;}
  function closeEnchantMaterialExchange(){const host=byId("enchantMaterialExchangeWindow");if(!host)return;host.classList.add("hidden-window");host.hidden=true;}
  function setEnchantExchangeGroup(id){if(!(data()?.groups||[]).some(row=>row.id===id))return;state.groupId=id;const rows=visibleRecipes();if(!rows.some(row=>row.id===state.selectedRecipeId))state.selectedRecipeId=rows[0]?.id||null;renderAll();}
  function setEnchantExchangeSearch(value){state.search=String(value||"").trim().toLowerCase();const rows=visibleRecipes();if(!rows.some(row=>row.id===state.selectedRecipeId))state.selectedRecipeId=rows[0]?.id||null;renderCatalog();renderDetail();}
  function selectEnchantExchangeRecipe(id){if(!recipeMap().has(String(id)))return;state.selectedRecipeId=String(id);renderCatalog();renderDetail();}
  function setEnchantExchangeQuantity(value){state.quantity=clampQuantity(value);const input=byId("enchantExchangeQuantity");if(input&&Number(input.value)!==state.quantity)input.value=state.quantity;renderDetail();}
  function inspectExchangeItem(id){const row=item(id);window.openEnchantStoneInfo?.({id:row.id,name:row.name,effect:Array.isArray(row.description)?row.description.join("\n"):row.description||""},`材料資訊｜持有 ${inventoryCount(id)}`);}
  function executeEnchantMaterialExchange(){const recipe=selectedRecipe(),quantity=state.quantity;if(!recipe){setMessage("請先選擇兌換配方。");return;}if(!materialsEnough(recipe,quantity)){setMessage("材料或 Zeny 不足。");renderDetail();return;}const output=item(recipe.output.id),total=n(recipe.output.amount,1)*quantity;if(!window.confirm?.(`確定製作 ${output.name} ×${total} 嗎？`))return;const snap=snapshot();try{(recipe.inputs||[]).forEach(row=>consume(row.id,n(row.amount)*quantity));window.player.zeny=n(window.player.zeny)-n(recipe.zeny)*quantity;grant(recipe.output.id,total);window.updateInventoryUI?.();window.updatePlayerUI?.();window.saveGame?.();window.addBattleLog?.(`材料兌換成功：${output.name} ×${total}`);setMessage(`兌換成功：${output.name} ×${total}`);renderAll();}catch(error){restore(snap);renderAll();setMessage(`兌換失敗：${error?.message||error}`);}}

  function renderAll(){renderGroups();renderCatalog();renderDetail();}
  function renderGroups(){const host=byId("enchantExchangeGroups");if(!host)return;host.innerHTML=(data()?.groups||[]).map(row=>`<button type="button" class="${state.groupId===row.id?"is-active":""}" onclick="setEnchantExchangeGroup('${escapeHtml(row.id)}')"><b>${escapeHtml(row.name)}</b><small>${row.recipeIds?.length||0} 項</small></button>`).join("");}
  function renderCatalog(){const host=byId("enchantExchangeCatalog"),count=byId("enchantExchangeCount");if(!host)return;const rows=visibleRecipes();if(count)count.textContent=`${rows.length} / ${recipes().length}`;host.innerHTML=rows.length?rows.map(recipe=>{const output=item(recipe.output.id);return `<button type="button" class="enchant-exchange-item${String(state.selectedRecipeId)===String(recipe.id)?" is-selected":""}" onclick="selectEnchantExchangeRecipe('${escapeHtml(recipe.id)}')"><img src="${iconPath(output.id)}" alt="${escapeHtml(output.name)}"><span><b>${escapeHtml(output.name)}</b><small>產出 ×${n(recipe.output.amount,1)}｜${recipe.inputs?.length||0} 種材料</small></span></button>`;}).join(""):`<div class="enchant-preview-empty"><b>找不到配方</b><span>請更換分類或搜尋文字。</span></div>`;}
  function renderDetail(){const host=byId("enchantExchangeDetail"),footer=byId("enchantExchangeRequirement"),execute=byId("enchantExchangeExecute");if(!host||!footer||!execute)return;const recipe=selectedRecipe();if(!recipe){host.innerHTML=`<div class="enchant-preview-empty"><b>請選擇配方</b></div>`;footer.innerHTML="";execute.disabled=true;return;}const output=item(recipe.output.id),quantity=state.quantity,total=n(recipe.output.amount,1)*quantity;host.innerHTML=`<div class="enchant-exchange-detail-main"><img src="${iconPath(output.id)}" alt="${escapeHtml(output.name)}"><div><small>材料兌換配方</small><h3>${escapeHtml(output.name)} ×${total}</h3><code>Item ID ${output.id}</code></div></div><p>${escapeHtml(Array.isArray(output.description)?output.description.join("\n"):output.description||"尚無物品說明。")}</p><section><h4>兌換方式</h4><p>選擇製作數量後，確認下方材料與 Zeny 足夠，即可一次完成兌換。</p></section><div class="enchant-exchange-policy"><b>黯淡冰晶附魔材料</b><span>可先查看需求，再前往對應地圖蒐集材料。</span></div>`;
    footer.innerHTML=`<div class="enchant-exchange-recipe-materials">${(recipe.inputs||[]).map(row=>{const input=item(row.id),need=n(row.amount)*quantity,owned=inventoryCount(row.id),enough=owned>=need;return `<button type="button" class="enchant-exchange-material${enough?" is-enough":""}" onclick="inspectExchangeItem(${input.id})" title="${escapeHtml(input.name)}｜持有 ${owned}／需要 ${need}"><img src="${iconPath(input.id)}"><span><small>${escapeHtml(input.name)}</small><b>${owned} / ${need}</b></span></button>`;}).join("")}</div><label class="enchant-exchange-quantity">製作次數<input id="enchantExchangeQuantity" type="number" min="1" max="${maxBatch()}" value="${quantity}" oninput="setEnchantExchangeQuantity(this.value)"></label><div class="enchant-exchange-output"><small>本次產出</small><b>${escapeHtml(output.name)} ×${total}</b><span>所需 Zeny ${(n(recipe.zeny)*quantity).toLocaleString("zh-TW")}</span></div>`;
    const enabled=materialsEnough(recipe,quantity);execute.disabled=!enabled;execute.classList.toggle("is-ready",enabled);execute.textContent=enabled?`確認兌換 ×${quantity}`:"材料不足";}

  window.openEnchantMaterialExchange=openEnchantMaterialExchange;window.closeEnchantMaterialExchange=closeEnchantMaterialExchange;window.setEnchantExchangeGroup=setEnchantExchangeGroup;window.setEnchantExchangeSearch=setEnchantExchangeSearch;window.selectEnchantExchangeRecipe=selectEnchantExchangeRecipe;window.setEnchantExchangeQuantity=setEnchantExchangeQuantity;window.inspectExchangeItem=inspectExchangeItem;window.executeEnchantMaterialExchange=executeEnchantMaterialExchange;
  window.EnchantMaterialExchangeRuntime={version:VERSION,open:openEnchantMaterialExchange,close:closeEnchantMaterialExchange,getData:data,getState:()=>JSON.parse(JSON.stringify(state)),previewOnly:false,inventoryFiltered:false};
  document.addEventListener("keydown",event=>{if(event.key==="Escape"&&isOpen())closeEnchantMaterialExchange();});
})();
