const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const heading='<div class="auto-section-title">攻擊設定</div>';
const normal='<label class="auto-normal-attack"><input type="checkbox" id="autoCombatNormalAttackEnabled" checked> 使用普通攻擊</label>';
assert.strictEqual((html.match(/<div class="auto-section-title">攻擊設定<\/div>/g)||[]).length,1,'Attack heading must appear exactly once');
const h=html.indexOf(heading),n=html.indexOf(normal),s1=html.indexOf('id="autoCombatAttackEnabled1"'),buff=html.indexOf('<div class="auto-section-title">Buff 技能</div>');
assert(h>=0&&n>h&&s1>n&&buff>s1,'Attack heading must group normal attack and skill slots before Buff section');
assert([...html.matchAll(/\?v=([^"']+)/g)].every(m=>m[1]==='0.9.82FD'),'All entry cache keys must be FD');
console.log('Auto Battle Attack Heading 0.9.82FD: 3/3 PASS');
