const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const ROOT=path.resolve(__dirname,'..'),read=r=>fs.readFileSync(path.join(ROOT,r),'utf8'),j=r=>JSON.parse(read(r));
const runtime=j('data/skill_runtime/runtime_core_1_v1.json'),generated=j('data/skill_runtime/runtime_generated_all.json'),pending=j('data/skill_runtime/runtime_pending_review.json'),catalog=j('data/skill_runtime/runtime_formula_catalog.json'),skills=j('data/skills/skills_core_1.json').skills,copy=j('data/skill_runtime/runtime_copyable_skills.json');
const ids=[2446,2447,2448,2449,2450,2454,2455],names={2446:'大地墳場',2447:'鑽石星塵',2448:'劇毒猛擊',2449:'超自然波',2450:'雲殺',2454:'聖槍刺擊',2455:'搖籃曲'};
assert.strictEqual(runtime.version,'0.9.82BG');assert.strictEqual(Object.keys(runtime.skills).length,610);assert.strictEqual(generated.summary.officialRuntime,610);assert.strictEqual(generated.summary.pending,529);assert.strictEqual(pending.skills.length,529);assert.strictEqual(catalog.summary.officialRuntime,610);
const pendingIds=new Set(pending.skills.map(x=>Number(x.skillId)));for(const id of ids){assert(runtime.skills[String(id)]?.executionEnabled);assert(!pendingIds.has(id));assert.strictEqual(skills[String(id)].name,names[id]);assert.strictEqual(skills[String(id)].effectRuntime.runtimeVersion,'0.9.82BG');}
for(const id of [2446,2447,2448,2449,2450,2454]){const row=copy.reproduce.find(x=>x.skillId===id);assert(row?.enabled&&row?.runtimeReady,`reproduce ${id}`);}assert(!copy.reproduce.some(x=>x.skillId===2455),'Arrullo has no official reproduce flag');
function makeContext(){
 const target={name:'測試怪物',position:{x:100,y:200},currentHp:999999,maxHp:999999,mdef:0,stats:{int:60,luk:10,vit:1},runtimeState:{statuses:{}}};
 const player={hp:10000,maxHp:10000,sp:10000,maxSp:10000,baseLevel:100,jobLevel:60,position:{x:10,y:20},stats:{int:100,dex:100},activeBuffs:{},learnedSkills:{281:5,282:5,283:5,2451:5},equipment:{weapon:1}};
 const created=[],applied=[];
 const c={console,Date,JSON,Number,String,Array,Object,Set,Map,Boolean,Infinity,NaN,Math:Object.create(Math),window:null,player,currentMonster:target,activeMonsters:[target],mapMonsters:[target],created,applied,
  skillsData:{runtimeProfiles:Object.fromEntries(ids.map(id=>[String(id),runtime.skills[String(id)]])),skillIndex:Object.fromEntries(ids.map(id=>[String(id),skills[String(id)]]))},
  getSkillLevel:id=>Number(player.learnedSkills[String(id)]||0),getCurrentJobSkills:()=>ids.map(id=>skills[String(id)]),getExtraSkillSkillList:()=>[],getItemData:()=>({dbSubType:'Staff'}),
  calculateDerivedPlayerStats:()=>({matk:100,matkMin:100,matkMax:100,stats:{int:100,dex:100,luk:1},sMatk:0}),addBattleLog(){},updatePlayerUI(){},updateMonsterUI(){},saveGame(){},recalculatePlayerStats(){},playMonsterHitAnimation(){},showDamageNumber(){},playPlayerAttackAnimation(){},playROStudioPlayerMotion(){},isPlayerMounted:()=>false,getSkillRangePx:()=>99999,canAttackMonsterByRange:()=>true,movePlayerTowardMonster(){},document:{getElementById(){return null}},requestAnimationFrame:f=>f(),setTimeout:f=>{f();return 1},clearTimeout(){},setInterval:()=>1,clearInterval(){},RO_WEB_CELL_SIZE:32};
 c.Math.random=()=>0;c.window=c;c.TargetingResolver={collect(origin,candidates){return (candidates||[]).filter(Boolean)}};c.MultiHitResolver={normalize(profile,level){const v=x=>Array.isArray(x)?Number(x[level-1]):Number(x||1);return {damageHitCount:Math.max(1,v(profile.damageHitCount)),visualHitCount:Math.max(1,v(profile.visualHitCount)),statusProcMode:'once'};},split(total,hits){hits=Math.max(1,Number(hits));const q=Math.floor(total/hits),r=total-q*hits;return Array.from({length:hits},(_,i)=>q+(i<r?1:0));}};
 c.StatusManager={apply(t,status,opt){applied.push({t,status,opt});t.runtimeState.statuses[String(status).toLowerCase().replace(/[ _-]/g,'')]={id:status,effects:opt.effects||{},expiresAt:Date.now()+Number(opt.durationMs||0)};return {applied:true};},has(t,status){return !!t.runtimeState?.statuses?.[String(status).toLowerCase().replace(/[ _-]/g,'')];},chance(t,status,chance){return chance;}};
 c.CombatDamagePipeline={resolveMagicSkill(profile,level,t,opt={}){return {damage:Number(opt.ratio||0)*Number(opt.hits||1),element:profile.element};}};c.GroundEffectManager={create(opt){created.push(opt);return opt;}};return c;
}
const c=makeContext();vm.createContext(c);vm.runInContext(read('js/skill_engine.js'),c,{filename:'skill_engine.js'});
const dmg=(id,lv=5)=>{c.player.learnedSkills[String(id)]=lv;return c.calculateSkillAttackDamage(skills[String(id)],lv,c.currentMonster,{})};
assert.strictEqual(dmg(2446),2200);assert.strictEqual(dmg(2447),2200);assert.strictEqual(dmg(2448),2600);c.currentMonster.runtimeState.statuses.cloudpoison={effects:{}};assert.strictEqual(dmg(2448),3600);delete c.currentMonster.runtimeState.statuses.cloudpoison;
assert.strictEqual(dmg(2449),1300);assert.strictEqual(dmg(2450),500);assert.strictEqual(dmg(2454,10),2199);
c.player.learnedSkills['2449']=5;assert.strictEqual(c.castGroundDamageSkill(skills['2449'],5),true);let ground=c.created.at(-1);assert.strictEqual(ground.rangeCells,5);assert.strictEqual(ground.tickMs,500);assert.strictEqual(ground.durationMs,3200);
c.player.learnedSkills['2450']=5;assert.strictEqual(c.castGroundDamageSkill(skills['2450'],5),true);ground=c.created.at(-1);ground.onTick([c.currentMonster]);assert(c.applied.some(x=>x.status==='cloud_poison'&&x.opt.durationMs===5000));
c.player.learnedSkills['2455']=5;assert.strictEqual(c.castTimedStatusSkill(skills['2455'],5),true);const sleep=c.applied.find(x=>x.status==='deep_sleep');assert(sleep);assert.strictEqual(Math.round(sleep.opt.chancePercent),61);assert.strictEqual(sleep.opt.durationMs,16000);assert.strictEqual(sleep.opt.effects.allDamageTakenRate,50);
// Actual periodic and damage-clear behavior.
const sctx={console,Date,JSON,Number,String,Array,Object,Set,Map,Boolean,Infinity,NaN,Math:Object.create(Math),window:null,player:{},setInterval:()=>1,clearInterval(){},showDamageNumber(){},addBattleLog(){},calculateDerivedPlayerStats:()=>({}),getMonsterRuntimeBonuses(t){const out={};for(const st of Object.values(t.runtimeState?.statuses||{}))for(const [k,v] of Object.entries(st.effects||{}))out[k]=(out[k]||0)+Number(v||0);return out;},applyROCombatDamageModifiers:d=>d,getActiveBuffBonusTotals:()=>({}),getPassiveSkillBonusTotals:()=>({}),getTrainingBonusTotals:()=>({}),getEquipmentCombatBonusTotals:()=>({}),getEquipmentModifierList:()=>[],getWeaponRuntimeInfo:()=>({}),getEquippedWeaponTypeRuntime:()=>'',ResourceFormulaResolver:{inputs:()=>({})}};sctx.window=sctx;sctx.Math.random=()=>0;vm.createContext(sctx);vm.runInContext(read('js/combat_mechanics_runtime.js'),sctx);vm.runInContext(read('js/ra_renewal_damage_pipeline.js'),sctx);
const crystal={currentHp:1000,maxHp:1000,runtimeState:{statuses:{}}};sctx.StatusManager.apply(crystal,'crystalize',{chancePercent:100,durationMs:20000,effects:{periodicDamageMaxHpPercent:2,periodicDamageIntervalMs:1000,periodicDamageNonLethal:true,windMagicDamageTakenRate:50,clearOnFireDamage:1}});const cs=crystal.runtimeState.statuses.crystalize;sctx.StatusManager.tickPeriodic(crystal,cs.nextPeriodicAt);assert.strictEqual(crystal.currentHp,980);assert.strictEqual(sctx.RARenewalDamagePipeline.finalModifiers(100,crystal,{damageType:'magic',element:'Wind',applyDefense:false,minimumDamage:0}),150);sctx.RARenewalDamagePipeline.finalModifiers(100,crystal,{damageType:'magic',element:'Fire',applyDefense:false,minimumDamage:0});assert(!crystal.runtimeState.statuses.crystalize);
const sleeper={currentHp:500,maxHp:1000,runtimeState:{statuses:{}}};sctx.StatusManager.apply(sleeper,'deep_sleep',{chancePercent:100,durationMs:16000,effects:{rooted:1,blocksActions:1,allDamageTakenRate:50,clearOnDamage:1,periodicHealMaxHpPercent:3,periodicHealIntervalMs:2000}});const ds=sleeper.runtimeState.statuses.deepsleep;sctx.StatusManager.tickPeriodic(sleeper,ds.nextPeriodicAt);assert.strictEqual(sleeper.currentHp,530);assert.strictEqual(sctx.RARenewalDamagePipeline.finalModifiers(100,sleeper,{damageType:'magic',element:'Neutral',applyDefense:false,minimumDamage:0}),150);assert(!sleeper.runtimeState.statuses.deepsleep);
console.log(JSON.stringify({result:'PASS',version:'0.9.82BG',official:610,pending:529,mageOfficial:86,magePending:67,formulas:{earthGrave:2200,diamondDust:2200,poisonBuster:2600,poisonBusterCloud:3600,psychicWaveStaff:1300,cloudKill:500,varetyrSpearTotal:2199},arrulloChance:61},null,2));
