const fs=require('fs'),vm=require('vm'),assert=require('assert');
const ctx={window:null,console,Math,Date,Number,String,Array,Object,Map,Set,Boolean,Infinity,NaN,setTimeout:()=>1,clearTimeout(){}};ctx.window=ctx;ctx.RO_WEB_CELL_SIZE=36;ctx.player={position:{x:0,y:0}};ctx.currentMonster=null;ctx.getActiveBuffBonusTotals=()=>({});ctx.calculateDerivedPlayerStats=()=>({});ctx.getPassiveCombatModifierTotals=()=>({});ctx.addBattleLog=()=>{};
vm.runInNewContext(fs.readFileSync('js/combat_mechanics_runtime.js','utf8'),ctx,{filename:'combat_mechanics_runtime.js'});
const m=(name,x,y)=>({name,currentHp:100,position:{x,y}});
const east=m('east',180,0), eastWide=m('eastWide',180,60), west=m('west',-100,0), north=m('north',0,-100), dead={...m('dead',50,0),currentHp:0};
let rows=ctx.TargetingResolver.collect(ctx.player,[east,eastWide,west,north,dead],{shape:'directed_line',rangeCells:6,widthCells:5,directionTarget:east,maxTargets:14});
assert(rows.includes(east));assert(rows.includes(eastWide));assert(!rows.includes(west));assert(!rows.includes(dead));
rows=ctx.TargetingResolver.collect(ctx.player,[east,eastWide,west,north],{shape:'cone',rangeCells:6,halfAngleRadians:Math.PI/4,directionTarget:north,maxTargets:10});
assert(rows.includes(north),'cone must face directionTarget');assert(!rows.includes(east),'north-facing cone must exclude east target');
rows=ctx.TargetingResolver.collect(ctx.player,[east,eastWide,west,north],{shape:'circle',rangeCells:6,maxTargets:2});assert.strictEqual(rows.length,2);
console.log(JSON.stringify({version:'0.9.82EV',status:'PASS',directedLine:2,coneDirectionTarget:true,deadFiltered:true,maxTargets:true},null,2));
