const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');const load=r=>vm.runInThisContext(fs.readFileSync(path.join(root,r),'utf8'),{filename:r});
const assert=(c,m)=>{if(!c)throw new Error(m)};
global.window=global;global.setInterval=()=>1;global.clearInterval=()=>{};global.RO_WEB_CELL_SIZE=32;
global.player={baseLevel:200,jobLevel:60,stats:{str:50,agi:50,vit:50,int:50,dex:50,luk:50,pow:20,con:30,spl:20},equipment:{weapon:1},learnedSkills:{},activeBuffs:{},extraSkills:{plagiarism:{skillId:5,level:10,sourceType:'plagiarism'}},position:{x:0,y:0}};
global.currentMonster={currentHp:999999,maxHp:999999,race:'Demon',size:'Large',element:'Neutral',def:0,mdef:0,position:{x:64,y:0}};
global.getItemData=()=>({weaponType:'dagger',atk:100,weaponLevel:4,element:'Neutral'});
global.calculateDerivedPlayerStats=()=>({atk:400,matk:300,matkMin:300,matkMax:300,hit:300,flee:200,stats:player.stats});
global.getTrainingBonusTotals=()=>({});global.getPassiveTargetDamageBonus=()=>0;global.getDualWieldHandRateTotals=()=>({active:false,right:100,left:0});global.getActiveBuffSpecialValue=(k,f)=>f;
global.getCurrentJobSkills=()=>[];global.getCurrentWeaponType=()=> 'dagger';global.isPlayerMounted=()=>false;global.getSkillLevel=id=>10;global.getNativeSkillLevel=id=>Number(id)===225?10:0;
global.skillsData={runtimeProfiles:{},skillIndex:{'5':{id:5,maxLevel:10,name:'狂擊'},'19':{id:19,maxLevel:10,name:'火箭術'}},copyableSkills:{plagiarism:[{skillId:19,maxLevel:10,runtimeReady:true,name:'火箭術',skillKey:'MG_FIREBOLT'}],reproduce:[]}};
global.CombatDamagePipeline={resolvePhysicalSkill:(p,l,t,o)=>({damage:o.ratio}),resolveMagicSkill:(p,l,t,o)=>({damage:o.ratio*(o.hits||1)}),resolveMiscSkill:(p,l,t,o)=>({damage:o.rawDamage||0})};
global.document={addEventListener:()=>{},getElementById:()=>null};global.saveGame=()=>{};global.updateSkillUI=()=>{};global.updateQuickSlotUI=()=>{};let logs=[];global.addBattleLog=x=>logs.push(x);
load('js/combat_mechanics_runtime.js');load('js/skill_engine.js');
const profs=JSON.parse(fs.readFileSync(path.join(root,'data/skill_runtime/runtime_core_1_v1.json'),'utf8')).skills;skillsData.runtimeProfiles=profs;
function dmg(id,lv,opt={}){return calculateSkillAttackDamage({id,maxLevel:lv},lv,currentMonster,opt)}
assert(dmg(5314,5)===14900,'Abyss Dagger formula');
player.activeBuffs={6512:{effects:{chasing:1},expiresAt:Date.now()+60000}};
assert(dmg(5315,5)===28400,'Unlucky Rush chasing formula');
assert(dmg(5316,5)===9400,'Chain primary formula');
assert(dmg(5316,5,{secondaryStage:true})===35000,'Chain secondary formula');
assert(dmg(5319,10)===57400,'Omega Abyss Strike formula');
assert(dmg(5320,10)===12680,'Deft Stab formula');
assert(dmg(5321,5)===11700,'Abyss Square formula');
assert(dmg(5322,10)===17400,'Frenzy Shot formula');
assert(dmg(6512,5)===35200,'Hit and Sliding formula');
assert(dmg(6513,5)===8700,'Chasing Break formula');
assert(dmg(6514,5)===12800,'Chasing Shot formula');
assert(dmg(6515,5)===18500,'Abyss Flame formula');
// Preserve blocks monster overwrite but manual selector remains a separate path.
load('js/extra_skill_runtime.js');
player.activeBuffs={'475':{effects:{copyProtection:1},expiresAt:Date.now()+60000}};
const blocked=onPlayerHitByCopyableSkill(19,5,'plagiarism');
assert(blocked===false,'Preserve must block monster overwrite');
assert(player.extraSkills.plagiarism.skillId===5,'Preserve changed copied slot');
player.activeBuffs={};
const copied=onPlayerHitByCopyableSkill(19,5,'plagiarism');
assert(copied===true,'Copy should work without Preserve');
assert(player.extraSkills.plagiarism.skillId===19,'Copy slot did not update');
console.log(JSON.stringify({result:'PASS',formulas:{abyssDagger:14900,unluckyRush:28400,chainPrimary:9400,chainSecondary:35000,omega:57400,deftStab:12680,abyssSquare:11700,frenzy:17400,hitSliding:35200,chasingBreak:8700,chasingShot:12800,abyssFlame:18500},preserve:'PASS'},null,2));
