const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');const load=r=>vm.runInThisContext(fs.readFileSync(path.join(root,r),'utf8'),{filename:r});
const assert=(c,m)=>{if(!c)throw new Error(m)};
global.window=global;global.setInterval=()=>1;global.clearInterval=()=>{};global.RO_WEB_CELL_SIZE=32;
const profiles=JSON.parse(fs.readFileSync(path.join(root,'data/skill_runtime/runtime_core_1_v1.json'),'utf8')).skills;
global.player={baseLevel:200,stats:{str:50,agi:50,vit:50,int:50,dex:50,luk:50},equipment:{weapon:1},learnedSkills:{5311:10,5312:10},activeBuffs:{2287:{effects:{damageRate:5},expiresAt:Date.now()+60000}}};
global.currentMonster={currentHp:100000,maxHp:100000,race:'Formless',size:'Large',element:'Neutral',elementLevel:1,def:0,mdef:0};
global.skillsData={runtimeProfiles:profiles};
global.getItemData=()=>({weaponType:'dagger',atk:100,weaponLevel:4,element:'Neutral'});
global.getCurrentWeaponType=()=> 'dagger';global.getSkillLevel=id=>Number(player.learnedSkills[id]||0);global.getCurrentJobSkills=()=>[{id:5311,officialId:5311,skillType:'passive',maxLevel:10},{id:5312,officialId:5312,skillType:'passive',maxLevel:10}];global.isPlayerMounted=()=>false;
global.calculateDerivedPlayerStats=()=>({atk:300,matk:200,matkMin:200,matkMax:200,stats:player.stats});global.getTrainingBonusTotals=()=>({});global.getPassiveTargetDamageBonus=()=>0;global.getDualWieldHandRateTotals=()=>({active:false,right:100,left:0});global.getActiveBuffSpecialValue=(k,f)=>f;
load('js/skill_engine.js');
const mods=getPassiveCombatModifierTotals();assert(mods.sizeDamage.Large===20,'Dagger/Bow Mastery large-size bonus');assert(mods.magicSizeDamage.Large===15,'Magic Sword Mastery large-size bonus');
global.applyROCombatDamageModifiers=n=>n;load('js/ra_renewal_damage_pipeline.js');
Math.random=()=>0;
const without=player.activeBuffs;player.activeBuffs={};const m0=RARenewalDamagePipeline.resolveMagicSkill({element:'Neutral',elementSource:'skill'},1,currentMonster,{ratio:100,hits:1}).damage;
player.activeBuffs=without;const m1=RARenewalDamagePipeline.resolveMagicSkill({element:'Neutral',elementSource:'skill'},1,currentMonster,{ratio:100,hits:1}).damage;
assert(m1>m0,'Shadow Form final damage did not affect magic damage');
console.log(JSON.stringify({result:'PASS',physicalLargeBonus:mods.sizeDamage.Large,magicLargeBonus:mods.magicSizeDamage.Large,magicWithoutShadow:m0,magicWithShadow:m1},null,2));
