const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),j=p=>JSON.parse(read(p));
const ids=[2201,2207,2214,5012];
const core=j('data/skill_runtime/runtime_core_1_v1.json'),generated=j('data/skill_runtime/runtime_generated_all.json'),catalog=j('data/skill_runtime/runtime_formula_catalog.json'),pending=j('data/skill_runtime/runtime_pending_review.json'),skills=j('data/skills/skills_core_1.json').skills,copy=j('data/skill_runtime/runtime_copyable_skills.json'),registry=j('data/skill_runtime/runtime_handler_registry.json');
assert.strictEqual(core.version,'0.9.82BG');assert.strictEqual(Object.keys(core.skills).length,610);assert.strictEqual(generated.summary.officialRuntime,610);assert.strictEqual(generated.summary.pending,529);assert.strictEqual(pending.skills.length,529);
for(const id of ids){assert(core.skills[String(id)]?.executionEnabled,`runtime ${id}`);assert.strictEqual(generated.skills[String(id)].implementationMode,'official');assert(!pending.skills.some(x=>Number(x.skillId)===id));assert.strictEqual(skills[String(id)].implementationStatus,'runtime_official');}
for(const id of [2209,2217,2222,2223,2224,2229,2230,2231,2232])assert(core.skills[String(id)]?.executionEnabled&& !pending.skills.some(x=>Number(x.skillId)===id),`expected official ${id}`);
const chainCopy=copy.reproduce.find(x=>Number(x.skillId)===2214);assert(chainCopy&&chainCopy.runtimeReady&&chainCopy.enabled);assert.strictEqual(copy.summary.reproduceRuntimeReady,100);assert.strictEqual(registry.handlers.chain_magic.executor,'castChainMagicSkill');assert.strictEqual(new Set(catalog.skills.map(x=>Number(x.skillId))).size,1139);
function makeMonster(name,x){return {name,position:{x,y:0},currentHp:100000,maxHp:100000,def:0,mdef:0,dex:1,stats:{mdef:0},runtimeState:{statuses:{}}};}
function context(){
 const target=makeMonster('A',0),player={hp:1000,maxHp:1000,sp:1000,maxSp:1000,baseLevel:100,jobLevel:60,activeBuffs:{},learnedSkills:Object.fromEntries(ids.map(id=>[String(id),5])),stats:{int:100,dex:100}};
 const logs=[];const c={console,Date,JSON,Number,String,Array,Object,Set,Map,Boolean,Infinity,NaN,Math:Object.create(Math),window:null,player,currentMonster:target,activeMonsters:[target],mapMonsters:[target],skillsData:{runtimeProfiles:Object.fromEntries(ids.map(id=>[String(id),core.skills[String(id)]])),skillIndex:Object.fromEntries(ids.map(id=>[String(id),skills[String(id)]]))},getSkillLevel:id=>Number(player.learnedSkills[String(id)]||0),getCurrentJobSkills:()=>ids.map(id=>skills[String(id)]),getExtraSkillSkillList:()=>[],calculateDerivedPlayerStats:()=>({matkMin:100,matkMax:100,matk:100,stats:{int:100,dex:100}}),getActiveBuffBonusTotals:()=>Object.values(player.activeBuffs).reduce((o,b)=>(Object.entries(b.effects||{}).forEach(([k,v])=>{if(typeof v==='number')o[k]=(o[k]||0)+v;}),o),{}),normalizeActiveBuffs(){},getPassiveSkillBonusTotals:()=>({}),addBattleLog:x=>logs.push(x),updatePlayerUI(){},updateMonsterUI(){},saveGame(){},recalculatePlayerStats(){},playMonsterHitAnimation(){},showDamageNumber(){},playPlayerAttackAnimation(){},playROStudioPlayerMotion(){},isPlayerMounted:()=>false,hasEquippedShieldRuntime:()=>false,getSkillRangePx:()=>99999,canAttackMonsterByRange:()=>true,movePlayerTowardMonster(){},document:{getElementById(){return null}},requestAnimationFrame:f=>f(),setTimeout:f=>{f();return 1},clearTimeout(){},setInterval:()=>1,clearInterval(){},RO_WEB_CELL_SIZE:32,logs};c.Math.random=()=>0;c.window=c;return c;
}
const c=context();vm.createContext(c);for(const f of ['js/combat_mechanics_runtime.js','js/ra_renewal_damage_pipeline.js','js/combat_damage_pipeline.js','js/skill_engine.js'])vm.runInContext(read(f),c);
// White Imprison: formula, immunity, Ghost break and natural-expiry damage.
assert.strictEqual(c.castTimedStatusSkill(skills['2201'],5),true);assert(c.StatusManager.has(c.currentMonster,'white_imprison'));let state=c.currentMonster.runtimeState.statuses.whiteimprison;assert(state&&state.effects.blocksActions===1&&state.effects.expireDamageFlat===2000);assert.strictEqual(state.chance,undefined);
let nonGhost=c.CombatDamagePipeline.resolveMagicSkill({elementSource:'fixed',element:'Fire'},5,c.currentMonster,{ratio:100,hits:1});assert.strictEqual(nonGhost.damage,0);assert(c.StatusManager.has(c.currentMonster,'white_imprison'));
let ghost=c.CombatDamagePipeline.resolveMagicSkill({elementSource:'fixed',element:'Ghost'},5,c.currentMonster,{ratio:100,hits:1});assert.strictEqual(ghost.damage,100);assert(!c.StatusManager.has(c.currentMonster,'white_imprison'));
c.castTimedStatusSkill(skills['2201'],5);state=c.currentMonster.runtimeState.statuses.whiteimprison;const hpBeforeExpire=c.currentMonster.currentHp;state.expiresAt=Date.now()-1;c.StatusManager.clearExpired(c.currentMonster);assert.strictEqual(c.currentMonster.currentHp,hpBeforeExpire-2000);
// Sienna: primary gate then area stone; item/SP costs remain zero in Runtime.
const b=makeMonster('B',64);c.currentMonster=makeMonster('A2',0);c.activeMonsters=[c.currentMonster,b];c.window.currentMonster=c.currentMonster;c.window.activeMonsters=c.activeMonsters;assert.strictEqual(c.castTimedStatusSkill(skills['2207'],5),true);assert(c.StatusManager.has(c.currentMonster,'stone'));assert(c.StatusManager.has(b,'stone'));assert.strictEqual(c.currentMonster.runtimeState.statuses.stone.effects.blocksActions,1);
// Intense Telekinesis: variable cast reduction and Ghost-only magic bonus.
c.currentMonster=makeMonster('C',0);c.window.currentMonster=c.currentMonster;assert.strictEqual(c.castBuffSkill(skills['5012'],5),true);const cast=c.getRuntimeAdjustedCastTime({castTime:1000,fixedCastTime:0},5);assert.strictEqual(cast.variableReductionRate,50);assert.strictEqual(cast.variableMs,500);ghost=c.CombatDamagePipeline.resolveMagicSkill({elementSource:'fixed',element:'Ghost'},5,c.currentMonster,{ratio:100,hits:1});assert.strictEqual(ghost.damage,300);const fire=c.CombatDamagePipeline.resolveMagicSkill({elementSource:'fixed',element:'Fire'},5,c.currentMonster,{ratio:100,hits:1});assert.strictEqual(fire.damage,100);
// Chain Lightning: 9 bounces with nearby alternatives, but only 4 hits against a lone target.
c.CombatDamagePipeline.resolveMagicSkill=(profile,level,target,opt)=>({damage:Number(opt.ratio),element:'Wind'});
const a=makeMonster('A3',0),d=makeMonster('D',32),e=makeMonster('E',64);c.currentMonster=a;c.activeMonsters=[a,d,e];c.window.currentMonster=a;c.window.activeMonsters=c.activeMonsters;let totalBefore=c.activeMonsters.reduce((n,m)=>n+m.currentHp,0);assert.strictEqual(c.castChainMagicSkill(skills['2214'],5),true);let totalAfter=c.activeMonsters.reduce((n,m)=>n+m.currentHp,0);assert.strictEqual(totalBefore-totalAfter,11700);
const lone=makeMonster('Lone',0);c.currentMonster=lone;c.activeMonsters=[lone];c.window.currentMonster=lone;c.window.activeMonsters=c.activeMonsters;const loneBefore=lone.currentHp;assert.strictEqual(c.castChainMagicSkill(skills['2214'],5),true);assert.strictEqual(loneBefore-lone.currentHp,6200);
console.log('Warlock prison/chain/telekinesis 0.9.82BG: PASS');process.exit(0);
