const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const ROOT=path.resolve(__dirname,'..'),read=r=>fs.readFileSync(path.join(ROOT,r),'utf8'),j=r=>JSON.parse(read(r));
const runtime=j('data/skill_runtime/runtime_core_1_v1.json'),generated=j('data/skill_runtime/runtime_generated_all.json'),pending=j('data/skill_runtime/runtime_pending_review.json'),catalog=j('data/skill_runtime/runtime_formula_catalog.json'),skills=j('data/skills/skills_core_1.json').skills;
const ids=[276,288,2443,2444,2445],names={276:'魔法懲罰',288:'地元素領域',2443:'火焰步',2444:'電流步',2445:'魔力拳'};
assert.strictEqual(runtime.version,'0.9.82BL');assert.strictEqual(Object.keys(runtime.skills).length,644);assert.strictEqual(generated.summary.officialRuntime,644);assert.strictEqual(generated.summary.pending,495);assert.strictEqual(pending.skills.length,495);assert.strictEqual(catalog.summary.officialRuntime,644);
const pendingIds=new Set(pending.skills.map(x=>Number(x.skillId)));for(const id of ids){assert(runtime.skills[String(id)]?.executionEnabled,`runtime ${id}`);assert(!pendingIds.has(id));assert.strictEqual(skills[String(id)].name,names[id]);assert.strictEqual(skills[String(id)].effectRuntime.runtimeVersion,'0.9.82BL');}assert(pendingIds.has(373));assert(pendingIds.has(402));
function makeContext(){
 const target={name:'測試怪物',race:'Formless',element:'Neutral',elementLevel:1,position:{x:100,y:200},currentHp:9999999,maxHp:9999999,mdef:0,def:0,stats:{int:0,luk:0,vit:0},runtimeState:{statuses:{}}};
 const learned={276:5,288:5,2443:5,2444:5,2445:10,14:10,19:10,20:10};
 const player={hp:10000,maxHp:10000,sp:1000,maxSp:1000,baseLevel:100,jobLevel:60,position:{x:0,y:0},stats:{int:100,dex:100},traitStats:{spl:0},activeBuffs:{},runtimeState:{statuses:{}},learnedSkills:learned,equipment:{weapon:1}};
 const allIds=[...ids,14,19,20],profiles={},index={};for(const id of allIds){if(runtime.skills[String(id)])profiles[String(id)]=runtime.skills[String(id)];if(skills[String(id)])index[String(id)]=skills[String(id)];}
 const logs=[];const c={console,Date,JSON,Number,String,Array,Object,Set,Map,Boolean,Infinity,NaN,Math:Object.create(Math),window:null,player,currentMonster:target,activeMonsters:[target],mapMonsters:[target],logs,
  skillsData:{runtimeProfiles:profiles,skillIndex:index},getSkillDataById:id=>index[String(id)]||null,getSkillLevel:id=>Number(player.learnedSkills[String(id)]||0),getCurrentJobSkills:()=>Object.values(index),getExtraSkillSkillList:()=>[],getItemData:()=>({dbSubType:'Staff',weaponLevel:1}),getEquippedWeaponTypeRuntime:()=> 'staff',
  calculateDerivedPlayerStats:()=>({matk:100,matkMin:100,matkMax:100,atk:100,hit:200,flee:100,stats:{int:100,dex:100,spl:0},sMatk:0}),addBattleLog(x){logs.push(x)},updatePlayerUI(){},updateMonsterUI(){},saveGame(){},recalculatePlayerStats(){},playMonsterHitAnimation(){},showDamageNumber(){},playPlayerAttackAnimation(){},playROStudioPlayerMotion(){},isPlayerMounted:()=>false,getSkillRangePx:()=>99999,canAttackMonsterByRange:()=>true,movePlayerTowardMonster(){},document:{getElementById(){return null}},requestAnimationFrame:f=>f(),setTimeout:f=>{f();return 1},clearTimeout(){},setInterval:()=>1,clearInterval(){},RO_WEB_CELL_SIZE:32,
  DefenseResolver:{physical:d=>d,magic:d=>d},getEquipmentCombatBonusTotals:()=>({}),getEquipmentModifierList:()=>[],getWeaponRuntimeInfo:()=>({}),getTrainingBonusTotals:()=>({damageRate:0}),ResourceFormulaResolver:{inputs:()=>({})}};
 c.Math.random=()=>0;c.window=c;return c;
}
const c=makeContext();vm.createContext(c);for(const file of ['js/combat_mechanics_runtime.js','js/skill_engine.js','js/combat_formula_runtime.js','js/ra_renewal_damage_pipeline.js','js/combat_damage_pipeline.js'])vm.runInContext(read(file),c,{filename:file});
// Magic Rod Lv5 absorbs single-target magic and restores 100% of its original SP cost.
assert.strictEqual(c.castBuffSkill(skills['276'],5),true);c.player.sp=500;const rod=c.resolveMagicRodIncomingDamage(777,40,{name:'測試魔法'},{singleTarget:true});assert.strictEqual(rod.absorbed,true);assert.strictEqual(rod.damage,0);assert.strictEqual(rod.spRestored,40);assert.strictEqual(c.player.sp,540);
// Land Protector removes existing ground magic and blocks new effects in the protected area.
c.currentMonster.position={x:100,y:200};const oldGround=c.GroundEffectManager.create({id:'old_ground',x:100,y:200,rangeCells:1,durationMs:10000,isGroundMagic:true,onTick(){}});assert(oldGround);assert.strictEqual(c.castGroundProtectionSkill(skills['288'],5),true);assert(!c.GroundEffectManager.effects.has('old_ground'));const blocked=c.GroundEffectManager.create({id:'blocked_ground',x:100,y:200,rangeCells:1,durationMs:10000,isGroundMagic:true,onTick(){}});assert.strictEqual(blocked,null);assert.strictEqual(c.GroundEffectManager.lastBlockReason,'land_protector');
// Fire Walk creates a trail after one cell of movement; Lv5, BaseLv100 = 300% MATK per tick.
c.GroundEffectManager.effects.clear();c.player.activeBuffs={};c.currentMonster.position={x:0,y:0};c.currentMonster.currentHp=9999999;assert.strictEqual(c.castBuffSkill(skills['2443'],5),true);c.createPropertyWalkTrailAt({x:0,y:0});assert.strictEqual(c.createPropertyWalkTrailAt({x:32,y:0}),true);assert.strictEqual(c.GroundEffectManager.effects.size,1);const beforeWalk=c.currentMonster.currentHp;c.GroundEffectManager.update(Date.now()+5,[c.currentMonster]);const walkDamage=beforeWalk-c.currentMonster.currentHp;assert.strictEqual(walkDamage,300);
// Electric Walk is mutually exclusive with Fire Walk and carries Wind property.
assert.strictEqual(c.castBuffSkill(skills['2444'],5),true);assert(!c.player.activeBuffs['2443']);assert.strictEqual(c.player.activeBuffs['2444'].effects.propertyWalkElement,'Wind');
// Spell Fist selects the highest learned bolt and adds one melee magic hit; Lv10 + Bolt10 = 1200% MATK.
c.player.activeBuffs={};c.currentMonster.currentHp=9999999;assert.strictEqual(c.castBuffSkill(skills['2445'],10),true);assert.strictEqual(c.player.activeBuffs['2445'].effects.spellFistRatio,1200);const beforeFist=c.currentMonster.currentHp;assert.strictEqual(c.trySpellFistOnNormalAttack(c.currentMonster),true);const fistDamage=beforeFist-c.currentMonster.currentHp;assert.strictEqual(fistDamage,1200);
console.log(JSON.stringify({result:'PASS',version:'0.9.82BL',official:644,pending:495,mageOfficial:120,magePending:33,magicRod:rod,walkDamage,fistDamage,groundEffects:c.GroundEffectManager.effects.size},null,2));
