from pathlib import Path
import json,re,sys
ROOT=Path(__file__).resolve().parents[1]
checks=[]
def check(cond,label): checks.append((bool(cond),label))
server=json.loads((ROOT/'data/server_config.json').read_text(encoding='utf-8'))
check(server['server']['rates'].get('gradeMaterialDropRate')==100,'Server Config grade material rate is 100=1x')
check(server.get('version')=='0.9.82GL','server version GL')
npcs=json.loads((ROOT/'data/npcs.json').read_text(encoding='utf-8'))
cities=json.loads((ROOT/'data/cities.json').read_text(encoding='utf-8'))
storage_cities={x['cityId'] for x in npcs if x.get('type')=='storage'}
check(storage_cities=={x['id'] for x in cities},'all implemented cities have one storage endpoint')
check(all('account_storage' in x.get('features',[]) for x in cities),'all city feature lists expose storage')
storage=(ROOT/'js/storage_runtime.js').read_text(encoding='utf-8')
check('const STORAGE_CAPACITY = 200;' in storage,'storage capacity 200')
check(all(f'dataStorageCategory="{x}"' not in storage for x in []),'storage category syntax')
check('setStorageCategory' in storage and 'categoryOf(entry)' in storage,'three storage category runtime')
index=(ROOT/'index.html').read_text(encoding='utf-8')
for key,label in [('consume','消耗'),('equipment','裝備'),('item','道具')]:
 check(f'data-storage-category="{key}"' in index and f'>{label}<' in index,f'storage tab {label}')
player=(ROOT/'js/player.js').read_text(encoding='utf-8')
check('INVENTORY_VISIBLE_SLOT_COUNT = 30' in player,'backpack visible slots 30')
css=(ROOT/'css/style.css').read_text(encoding='utf-8')
check('repeat(5,minmax(0,1fr))' in css and 'visible-rows:6' in css,'backpack final CSS 5x6')
mapjs=(ROOT/'js/map.js').read_text(encoding='utf-8')
check('RO_MAP_MONSTER_DROP_CACHE = new Map()' in mapjs,'monster drop static cache')
check('data-monster-drop-id' in mapjs and 'renderMapMonsterDropDetail' in mapjs,'hover/tap drop detail')
check('setInterval(refreshMapMonsterDistributionTooltip' not in mapjs,'drop tooltip has no polling timer')
check('不參與掛機運算' in mapjs,'drop detail explicitly isolated from auto battle')
grade=(ROOT/'js/enchant_grade_runtime.js').read_text(encoding='utf-8')
check('getScaledGradeDropChance' in grade and '*getGradeMaterialDropRate()/100' in grade,'grade bonus percent multiplier calculation')
check('async function open(npc)' in grade and 'ensureGradeData' in grade and 'removeAttribute("hidden")' in grade,'grade window robust open and lazy data load')
status=(ROOT/'js/status_system.js').read_text(encoding='utf-8')
check('queueStatusAllocationCommit' in status,'status allocation batch commit')
check(all(x in status for x in ['"pointerup"','"touchend"','event.stopPropagation()']),'status input events isolated')
check('requestStatusUIUpdate({ force:true });' not in status[status.find('function allocateStatusPoints'):status.find('function resetAllPlayerStats')],'allocation avoids synchronous forced status rebuild')
skill=(ROOT/'js/skill_engine.js').read_text(encoding='utf-8')
check('isCopiedSkillResourceWaived' in skill and 'skill.extraSkill===true' in skill,'copied/reproduced resource exemption is source-aware')
check('((level + 1) * dex) * (jobLv / 10)' in skill,'Feint Bomb damage correction enabled')
check('applyRuntimeResourceCost(profile, level, skill)' in skill,'skill identity reaches resource consumption')
failed=[x for x in checks if not x[0]]
for ok,label in checks: print(('PASS' if ok else 'FAIL')+': '+label)
print(json.dumps({'version':'0.9.82GL','passed':len(checks)-len(failed),'total':len(checks),'failed':[x[1] for x in failed]},ensure_ascii=False))
if failed: sys.exit(1)
