const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..'),j=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const core=j('data/skills/skills_core_1.json').skills,runtime=j('data/skill_runtime/runtime_core_1_v1.json').skills;
const generated=j('data/skill_runtime/runtime_generated_all.json'),pending=j('data/skill_runtime/runtime_pending_review.json'),copy=j('data/skill_runtime/runtime_copyable_skills.json');
const ids=[2233,2234,2235,2236,2248,5002];for(const id of ids){assert(runtime[id]?.executionEnabled,`runtime ${id}`);assert(generated.skills[id]?.executionEnabled,`generated ${id}`);assert(!pending.skills.some(x=>Number(x.skillId)===id));}
assert.strictEqual(generated.summary.officialRuntime,727);assert.strictEqual(generated.summary.pending,412);assert.strictEqual(core['5002'].name,'菁英狙擊');
for(const id of [2233,2236]){const row=copy.reproduce.find(x=>Number(x.skillId)===id);assert(row?.runtimeReady&&row?.enabled,`copy ${id}`);}
const ctx={window:null,console,Date,setTimeout:()=>0,clearTimeout:()=>{},setInterval:()=>0,clearInterval:()=>{},Math:Object.create(Math)};ctx.window=ctx;ctx.Math.random=()=>0.02;
ctx.skillsData={runtimeProfiles:runtime,skillIndex:core};ctx.player={jobKey:'ranger',baseLevel:200,jobLevel:70,hp:10000,maxHp:10000,sp:10000,maxSp:10000,stats:{str:1,agi:120,vit:1,int:100,dex:120,luk:90},equipment:{weapon:1},learnedSkills:{2233:10,2234:5,2235:10,2236:10,2248:10,5002:5},activeBuffs:{},position:{x:0,y:0}};
const brute={name:'Brute',currentHp:999999,maxHp:999999,element:'Neutral',race:'Brute',size:'Medium',position:{x:64,y:0},stats:{luk:0},hardDef:0,softDef:0};ctx.currentMonster=brute;ctx.activeMonsters=[brute];
ctx.getSkillLevel=id=>Number(ctx.player.learnedSkills[id]||0);ctx.getSkillDataById=id=>core[String(id)]||null;ctx.getCurrentJobSkills=()=>ids.map(id=>core[String(id)]);
ctx.calculateDerivedPlayerStats=()=>({stats:{str:1,agi:120,vit:1,int:100,dex:120,luk:90},atk:500,hit:300,cri:10,walkSpeed:100,pAtk:0});ctx.getTrainingBonusTotals=()=>({});ctx.getItemData=()=>({weaponType:'bow',dbSubType:'bow',atk:200,range:5});ctx.getEquippedWeaponTypeRuntime=()=> 'bow';
ctx.RO_WEB_CELL_SIZE=32;ctx.getCombatGroundCandidates=()=>ctx.activeMonsters;ctx.canAttackMonsterByRange=()=>true;ctx.addBattleLog=()=>{};ctx.showDamageNumber=()=>{};ctx.playMonsterHitAnimation=()=>{};ctx.updateMonsterUI=()=>{};ctx.updatePlayerUI=()=>{};ctx.saveGame=()=>{};ctx.recalculatePlayerStats=()=>{};ctx.defeatMonster=()=>{};
for(const file of ['js/combat_mechanics_runtime.js','js/combat_formula_runtime.js','js/ra_renewal_damage_pipeline.js','js/combat_damage_pipeline.js','js/position_engine.js','js/skill_engine.js'])vm.runInNewContext(fs.readFileSync(path.join(root,file),'utf8'),ctx,{filename:file});
ctx.getCurrentJobSkills=()=>ids.map(id=>core[String(id)]);
let passive=ctx.getPassiveSkillBonusTotals();assert.strictEqual(passive.intFlat,10);assert.strictEqual(passive.maxSpFlat,400);assert.strictEqual(passive.trapRangeCells,5);assert.strictEqual(ctx.getPassiveTargetDamageBonus(brute),50);
let pcm=ctx.getPassiveCombatModifierTotals();assert.strictEqual(pcm.flatRaceDamageReduction.Brute,50);ctx.getPassiveCombatModifierTotals=()=>pcm;
const incoming=ctx.applyROCombatDamageModifiers(1000,{damageType:'physical',source:brute,target:ctx.player,sourceRace:'Brute',sourceSize:'Medium',attackElement:'Neutral',applyWeaponSize:false,applyDefense:false});assert.strictEqual(incoming,950);
assert(ctx.castBuffSkill(core['2234'],5));let active=ctx.getActiveBuffBonusTotals();assert.strictEqual(active.fearBreezeLevel,5);
let proc=ctx.RARenewalDamagePipeline.fearBreezeProc(active,'bow');assert.strictEqual(proc.hits,5);ctx.Math.random=()=>0.05;proc=ctx.RARenewalDamagePipeline.fearBreezeProc(active,'bow');assert.strictEqual(proc.hits,4);ctx.Math.random=()=>0.08;proc=ctx.RARenewalDamagePipeline.fearBreezeProc(active,'bow');assert.strictEqual(proc.hits,3);ctx.Math.random=()=>0.11;proc=ctx.RARenewalDamagePipeline.fearBreezeProc(active,'bow');assert.strictEqual(proc.hits,2);
let dmg=ctx.calculateSkillAttackDamage(core['2233'],10,brute,{criticalResult:{critical:false,multiplier:1}});assert.strictEqual(ctx.lastRADamageTrace.ratio,Math.floor((200+2500)*2));assert(dmg>0);
dmg=ctx.calculateSkillAttackDamage(core['2236'],10,brute,{criticalResult:{critical:false,multiplier:1}});assert.strictEqual(ctx.lastRADamageTrace.ratio,Math.floor((800+350)*2));assert(dmg>0);
assert(ctx.castBuffSkill(core['5002'],5));active=ctx.getActiveBuffBonusTotals();assert.strictEqual(active.longPhysicalDamageRate,250);
const normal=ctx.RARenewalDamagePipeline.resolveNormalAttack(brute,{criticalResult:{critical:false,multiplier:1},procOverride:{key:'test',ratio:100,hits:1}});assert(normal.raw>0);const noUnlimited={...ctx.player.activeBuffs};delete ctx.player.activeBuffs['5002'];const normalBase=ctx.RARenewalDamagePipeline.resolveNormalAttack(brute,{criticalResult:{critical:false,multiplier:1},procOverride:{key:'test',ratio:100,hits:1}});ctx.player.activeBuffs=noUnlimited;assert(normal.raw>=Math.floor((normalBase.raw-50)*3.49+50));
const trap={id:115,officialId:115,range:3,flags:{IsTrap:true}};assert.strictEqual(ctx.getSkillRangeCells(trap),8);
console.log(JSON.stringify({result:'PASS',official:727,pending:412,passive,incoming,arrowStormRatio:5400,aimedBoltRatio:2300,trapRange:8},null,2));
