const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const ROOT=path.resolve(__dirname,'..'),read=r=>fs.readFileSync(path.join(ROOT,r),'utf8'),j=r=>JSON.parse(read(r));
const runtime=j('data/skill_runtime/runtime_core_1_v1.json'),generated=j('data/skill_runtime/runtime_generated_all.json'),pending=j('data/skill_runtime/runtime_pending_review.json'),catalog=j('data/skill_runtime/runtime_formula_catalog.json'),skills=j('data/skills/skills_core_1.json').skills;
const ids=[5365,5366,5369,5370,5371,5372,5373],names={5365:'魔法書精熟',5366:'咒力賦予',5369:'鑽石風暴',5370:'雷霆陣地',5371:'毒液沼澤',5372:'灼熱岩漿',5373:'大地驅動'};
assert.strictEqual(runtime.version,'0.9.82BJ');assert.strictEqual(Object.keys(runtime.skills).length,632);assert.strictEqual(generated.summary.officialRuntime,632);assert.strictEqual(generated.summary.pending,507);assert.strictEqual(pending.skills.length,507);assert.strictEqual(catalog.summary.officialRuntime,632);
const pendingIds=new Set(pending.skills.map(x=>Number(x.skillId)));for(const id of ids){assert(runtime.skills[String(id)]?.executionEnabled);assert(!pendingIds.has(id));assert.strictEqual(skills[String(id)].name,names[id]);assert.strictEqual(skills[String(id)].effectRuntime.runtimeVersion,'0.9.82BH');}
function makeContext(){
 const target={name:'測試怪物',position:{x:100,y:200},currentHp:999999,maxHp:999999,mdef:0,runtimeState:{statuses:{}}};
 const player={hp:10000,maxHp:10000,sp:10000,maxSp:10000,baseLevel:100,jobLevel:60,position:{x:10,y:20},stats:{int:100},traitStats:{spl:100},activeBuffs:{},learnedSkills:{5365:10,5366:5,5369:5,5370:5,5371:5,5372:5,5373:5},equipment:{weapon:1}};
 const created=[],applied=[];
 const c={console,Date,JSON,Number,String,Array,Object,Set,Map,Boolean,Infinity,NaN,Math:Object.create(Math),window:null,player,currentMonster:target,activeMonsters:[target],mapMonsters:[target],created,applied,
  skillsData:{runtimeProfiles:Object.fromEntries(ids.map(id=>[String(id),runtime.skills[String(id)]])),skillIndex:Object.fromEntries(ids.map(id=>[String(id),skills[String(id)]]))},
  getSkillLevel:id=>Number(player.learnedSkills[String(id)]||0),getCurrentJobSkills:()=>ids.map(id=>skills[String(id)]),getExtraSkillSkillList:()=>[],getItemData:()=>({dbSubType:'Book'}),
  calculateDerivedPlayerStats:()=>({matk:100,matkMin:100,matkMax:100,stats:{int:100,spl:100},sMatk:0}),addBattleLog(){},updatePlayerUI(){},updateMonsterUI(){},saveGame(){},recalculatePlayerStats(){},playMonsterHitAnimation(){},showDamageNumber(){},playPlayerAttackAnimation(){},playROStudioPlayerMotion(){},isPlayerMounted:()=>false,getSkillRangePx:()=>99999,canAttackMonsterByRange:()=>true,movePlayerTowardMonster(){},document:{getElementById(){return null}},requestAnimationFrame:f=>f(),setTimeout:f=>{f();return 1},clearTimeout(){},setInterval:()=>1,clearInterval(){},RO_WEB_CELL_SIZE:32};
 c.Math.random=()=>0;c.window=c;c.TargetingResolver={collect(origin,candidates){return (candidates||[]).filter(Boolean)}};c.MultiHitResolver={normalize(profile,level){const v=x=>Array.isArray(x)?Number(x[level-1]):Number(x||1);return {damageHitCount:Math.max(1,v(profile.damageHitCount)),visualHitCount:Math.max(1,v(profile.visualHitCount)),statusProcMode:'once'};},split(total,hits){hits=Math.max(1,Number(hits));const q=Math.floor(total/hits),r=total-q*hits;return Array.from({length:hits},(_,i)=>q+(i<r?1:0));}};
 c.StatusManager={apply(t,status,opt){applied.push({t,status,opt});return {applied:true};},has(){return false;}};c.CombatDamagePipeline={resolveMagicSkill(profile,level,t,opt={}){return {damage:Number(opt.ratio||0)*Number(opt.hits||1),element:profile.element};}};c.GroundEffectManager={create(opt){created.push(opt);return opt;}};return c;
}
const c=makeContext();vm.createContext(c);vm.runInContext(read('js/skill_engine.js'),c,{filename:'skill_engine.js'});
assert.strictEqual(c.calculateSkillAttackDamage(skills['5369'],5,c.currentMonster,{}),13000);assert.strictEqual(c.calculateSkillAttackDamage(skills['5373'],5,c.currentMonster,{}),13000);for(const id of [5370,5371,5372])assert.strictEqual(c.calculateSkillAttackDamage(skills[String(id)],5,c.currentMonster,{}),6700);
const mods=c.getPassiveCombatModifierTotals();for(const e of ['water','earth','fire','wind','poison'])assert.strictEqual(mods.magicElementDamage[e],10);
assert.strictEqual(c.castBuffSkill(skills['5366'],5),true);assert.strictEqual(c.player.activeBuffs['5366'].effects.sMatk,20);assert(Math.abs((c.player.activeBuffs['5366'].expiresAt-Date.now())-240000)<1000);
for(const id of [5370,5371,5372]){assert.strictEqual(c.castGroundDamageSkill(skills[String(id)],5),true);const g=c.created.at(-1);assert.strictEqual(g.rangeCells,4);assert.strictEqual(g.tickMs,300);assert.strictEqual(g.durationMs,3000);g.onTick([c.currentMonster]);}
assert(c.applied.some(x=>x.status==='lightning_strike'&&x.opt.durationMs===10000));assert(c.applied.some(x=>x.status==='deadly_poison'&&x.opt.durationMs===20000));assert(c.applied.some(x=>x.status==='conflagration'&&x.opt.durationMs===20000));
const pctx={console,Date,JSON,Number,String,Array,Object,Set,Map,Boolean,Infinity,NaN,Math:Object.create(Math),window:null,player:{matk:100,baseLevel:100},calculateDerivedPlayerStats:()=>({matk:100,matkMin:100,matkMax:100,stats:{},sMatk:0}),getActiveBuffBonusTotals:()=>({}),getPassiveSkillBonusTotals:()=>({}),getPassiveCombatModifierTotals:()=>({magicElementDamage:{water:10}}),getTrainingBonusTotals:()=>({damageRate:0}),applyROCombatDamageModifiers:d=>d,getMonsterRuntimeBonuses:()=>({}),getEquipmentCombatBonusTotals:()=>({}),getEquipmentModifierList:()=>[],getWeaponRuntimeInfo:()=>({}),getItemData:()=>null,ResourceFormulaResolver:{inputs:()=>({})}};pctx.window=pctx;pctx.Math.random=()=>0;vm.createContext(pctx);vm.runInContext(read('js/ra_renewal_damage_pipeline.js'),pctx);const out=pctx.RARenewalDamagePipeline.resolveMagicSkill({element:'Water',elementSource:'fixed'},5,{mdef:0},{ratio:100,hits:1});assert.strictEqual(out.raw,110);
console.log(JSON.stringify({result:'PASS',version:'0.9.82BJ',official:632,pending:507,mageOfficial:93,magePending:60,diamondStorm:13000,elementalField:6700,bookElementRate:10,spellEnchantingSMatk:20},null,2));
