const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),load=r=>JSON.parse(fs.readFileSync(path.join(root,r),'utf8')),assert=(v,m)=>{if(!v)throw new Error(m)};
const core=load('data/skills/skills_core_1.json'),runtime=load('data/skill_runtime/runtime_core_1_v1.json'),generated=load('data/skill_runtime/runtime_generated_all.json'),pending=load('data/skill_runtime/runtime_pending_review.json');
const ids=[5449,5450,5451,5452,5453,5454];
assert(runtime.version==='0.9.82CR','version');assert(generated.summary.officialRuntime===818,'official');assert(generated.summary.pending===321,'pending');
ids.forEach(id=>{assert(runtime.skills[String(id)]?.executionEnabled===true,'runtime '+id);assert(!pending.skills.some(x=>Number(x.skillId)===id),'pending '+id)});
let sandbox={console,window:null,document:{getElementById:()=>null,querySelector:()=>null,querySelectorAll:()=>[]},setInterval:()=>0,clearInterval:()=>{},setTimeout:()=>0,clearTimeout:()=>{},Date,Math:Object.create(Math)};sandbox.window=sandbox;
sandbox.player={baseLevel:200,jobLevel:60,stats:{str:1,agi:1,vit:1,int:1,dex:1,luk:1,pow:50},traitStats:{pow:50},learnedSkills:{'5449':10,'5450':10,'5451':10,'5452':10,'5453':10,'5454':10},activeBuffs:{},equipment:{},position:{x:0,y:0}};
sandbox.skillsData={skillIndex:{},runtimeProfiles:runtime.skills};ids.forEach(id=>sandbox.skillsData.skillIndex[String(id)]={...core.skills[String(id)],runtimeProfile:runtime.skills[String(id)].runtimeProfile});
sandbox.getSkillLevel=id=>Number(sandbox.player.learnedSkills[String(id)]||0);sandbox.getSkillDataById=id=>sandbox.skillsData.skillIndex[String(id)]||null;sandbox.getCurrentJobSkills=()=>ids.map(id=>sandbox.skillsData.skillIndex[String(id)]);sandbox.getExtraSkillSkillList=()=>[];sandbox.getEquippedWeaponTypeRuntime=()=> 'sword';sandbox.calculateDerivedPlayerStats=()=>({stats:{...sandbox.player.stats,pow:50},pAtk:10,sMatk:10});sandbox.CombatDamagePipeline={resolvePhysicalSkill:(p,l,t,o)=>({damage:Number(o.ratio)})};sandbox.MultiHitResolver={normalize:(p,l)=>({damageHitCount:Number(p.damageHitCount||1),visualHitCount:Number(p.visualHitCount||1)})};sandbox.StatusManager={apply:()=>({applied:true})};sandbox.addBattleLog=()=>{};sandbox.recalculatePlayerStats=()=>{};sandbox.updatePlayerUI=()=>{};sandbox.saveGame=()=>{};
vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(root,'js/skill_engine.js'),'utf8'),sandbox);
const passive=sandbox.getPassiveSkillBonusTotals();assert(passive.pAtk===10,'pAtk '+passive.pAtk);assert(passive.sMatk===10,'sMatk '+passive.sMatk);
const calc=(id,target)=>sandbox.calculateSkillAttackDamage(sandbox.skillsData.skillIndex[String(id)],10,target,{criticalResult:{critical:false,multiplier:1}});
assert(calc(5451,{currentHp:10000,maxHp:10000,size:'Medium'})===9600,'double bowling');
assert(calc(5452,{currentHp:4000,maxHp:10000,size:'Medium'})===36600,'mega sonic low hp');
assert(calc(5453,{currentHp:10000,maxHp:10000,size:'Medium'})===28300,'shield chain');
assert(calc(5454,{currentHp:10000,maxHp:10000,size:'Medium'})===43030,'spiral medium');
assert(runtime.skills['5453'].runtimeProfile.requiresShield===true,'shield requirement');assert(runtime.skills['5452'].runtimeProfile.statusChancePercent[9]===30,'stun chance');
console.log(JSON.stringify({result:'PASS',version:'0.9.82CR',official:818,pending:321,noviceFamily:'108/118',passive,ratios:{doubleBowling:9600,megaSonicLowHp:36600,shieldChain:28300,spiralMedium:43030}},null,2));
