const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const core=read('data/skill_runtime/runtime_core_1_v1.json');
const gen=read('data/skill_runtime/runtime_generated_all.json');
const pen=read('data/skill_runtime/runtime_pending_review.json');
const ids=[25,27,32,69,70,71,73,361,362,363];
for(const id of ids){if(!core.skills[String(id)])throw new Error(`missing runtime ${id}`);if(gen.skills[String(id)].implementationMode!=='official')throw new Error(`not official ${id}`);}
if(pen.skills.some(x=>ids.includes(Number(x.skillId))))throw new Error('implemented skill remains pending');
const warp=core.skills['27'].runtimeProfile.passiveBonuses.matkRate;
if(warp[3]!==12)throw new Error('Warp MATK rate mismatch');
const kyrie=core.skills['73'].runtimeProfile.effects;
if(kyrie.kyrieBarrierMaxHpRate[9]!==30||kyrie.kyrieBarrierHits[9]!==10)throw new Error('Kyrie mismatch');
const med=core.skills['363'].runtimeProfile.passiveBonuses;
if(med.maxSpRate[9]!==10||med.spRecoveryRate[9]!==30||med.healPowerRate[9]!==20)throw new Error('Meditatio mismatch');
const signumChance=Math.max(0,Math.min(100,25+4*10+200-180));
if(signumChance!==85)throw new Error('Signum formula mismatch');
const sanctuary=core.skills['70'].runtimeProfile;
if(sanctuary.heal[6]!==777||sanctuary.damageRatioPercent!==50)throw new Error('Sanctuary mismatch');
console.log(JSON.stringify({result:'PASS',official:gen.summary.official,pending:pen.summary.pending,signumChance,sanctuaryLv7Heal:sanctuary.heal[6],kyrieLv10Rate:kyrie.kyrieBarrierMaxHpRate[9],meditatioLv10:med},null,2));
