const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..'),read=r=>fs.readFileSync(path.join(root,r),'utf8'),j=r=>JSON.parse(read(r));
const mapJs=read('js/map.js'),skillEngine=read('js/skill_engine.js'),css=read('css/style.css'),index=read('index.html');
assert(!j('data/maps.json').some(m=>/3×3|RA Renewal|怪物池/.test(String(m.environment||'')+String(m.description||''))),'Map display strings must not expose technical 3x3/RA text');
assert(mapJs.includes('map-region-warp-button')&&mapJs.includes('map-city-hover-tip'),'Map region-only and city hover rendering missing');
assert(mapJs.includes(': `<b>${dest.name}</b>`'),'Field warp entries must render only region name');
const cities=j('data/cities.json');assert.strictEqual(cities.length,6);for(const c of cities)assert(c.hoverDescription&&c.hoverDescription.length>12,`${c.id} hover help missing`);
assert(skillEngine.includes('document.getElementById("player-sprite")'),'Cast bar must attach to player sprite');
assert(!skillEngine.includes('runtime-skill-cast-name"></div>'),'Cast bar must not contain skill text');
assert(!skillEngine.includes('開始詠唱 ${state.skillName}'),'Cast start battle-log text must be removed');
assert(css.includes('#runtime-skill-cast-bar')&&css.includes('top: 66px')&&css.includes('width: 72px'),'Head cast bar CSS missing');
assert([...index.matchAll(/\?v=([^"']+)/g)].every(m=>m[1]==='0.9.82EZ'),'All entry cache keys must be EZ');
// Dynamic job quest rule check.
const core={...j('data/skills/skills_core_1.json').skills,...j('data/skills/skills_core_2.json').skills};
const jobs=j('data/jobs.json');
const makeTree=(key)=>{const p=path.join(root,`data/skill_trees/${key}.json`);if(!fs.existsSync(p))return [];return j(`data/skill_trees/${key}.json`).skills.filter(n=>!n.exclude).map(n=>core[String(n.skillId)]).filter(Boolean)};
const ctx={window:null,console,document:undefined,Math,Date,JSON,Number,String,Object,Array,Set,Map};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(read('js/job.js'),ctx,{filename:'job.js'});
ctx.__core=core;ctx.__jobs=jobs;ctx.__trees={novice:makeTree('novice'),swordman:makeTree('swordman'),knight:makeTree('knight')};
vm.runInContext('jobs=__jobs; skillsData={skillIndex:__core,jobs:__trees}; player={jobKey:"high_novice",learnedSkills:{},stats:{},equipment:{}};',ctx);
assert.strictEqual(vm.runInContext('getSkillLevel(142)',ctx),1,'High Novice must automatically regain First Aid');
vm.runInContext('player.jobKey="swordman";',ctx);assert.strictEqual(vm.runInContext('getSkillLevel(144)',ctx),1,'Swordman quest skill must be directly owned');
assert.strictEqual(vm.runInContext('getSkillLevel(142)',ctx),1,'First Aid must remain auto-granted in applicable inherited trees');
vm.runInContext('__trees.knight=__trees.knight; player.jobKey="knight";',ctx);assert.strictEqual(vm.runInContext('getSkillLevel(1001)',ctx),1,'Knight quest skill must be directly owned');
console.log(JSON.stringify({version:'0.9.82EZ',status:'PASS',cities:cities.length,firstAidAfterRebirth:1,autoQuestSkills:[144,1001]},null,2));
