const fs = require('fs');
function assert(v,m){ if(!v) throw new Error(m); }
const battle = fs.readFileSync('js/battle.js','utf8');
const world = fs.readFileSync('js/world_monster_test_runtime.js','utf8');
const player = fs.readFileSync('js/player.js','utf8');
const loot = fs.readFileSync('js/loot.js','utf8');
const skill = fs.readFileSync('js/skill_engine.js','utf8');
const css = fs.readFileSync('css/style.css','utf8');
assert(/function captureDamageNumberAnchor\(target\)/.test(battle),'damage anchor capture helper');
assert(/_anchorSnapshot:captureDamageNumberAnchor\(target\)/.test(battle),'anchor captured at enqueue time');
assert(/const anchor = options\._anchorSnapshot/.test(battle),'queued anchor used during DOM creation');
assert(/_damageNumberAnchorScreen/.test(world) && /_damageNumberAnchorLocal/.test(world),'world renderer stores monster-top anchor');
assert(/fill\.style\.transform = `scaleX\(\$\{ratio\}\)`/.test(world),'HP bar uses compositor transform');
assert(/transition: transform \.035s linear/.test(css),'HP fill transition uses transform');
assert(/function queueMonsterDefeatResolution/.test(battle),'deferred defeat resolution exists');
assert(/requestIdleCallback/.test(battle),'death rewards scheduled outside damage frame');
const defeatBody = battle.match(/function defeatMonster\(\) \{([\s\S]*?)\n\}/)?.[1] || '';
assert(/queueMonsterDefeatResolution/.test(defeatBody),'primary defeat uses deferred queue');
assert(!/grantMonsterRewards/.test(defeatBody),'primary defeat does not grant synchronously');
assert(/RO_WEB_REWARD_BATCH_ACTIVE/.test(player) && /markRewardBatchDirty\("inventory"\)/.test(player),'inventory mutations are batched');
assert(/emitLootRewardLog/.test(loot),'reward logs are batched');
assert(/queueMonsterDefeatResolution\(target, \{ primary:false \}\)/.test(skill),'secondary AoE kills use same deferred queue');
assert(/if \(!player\?\.currentCity && currentMonster\?\._worldTestEntity/.test(battle),'hidden legacy monster panel skipped for streamed target');
console.log('PASS 0.9.82EW damage anchor, HP compositor update and deferred defeat rewards');
