const fs=require('fs'),vm=require('vm');
const ROOT='/mnt/data/roweb_gk_work';
global.window=global;global.document=undefined;
window.RO_WEB_DATA={};
for(const f of ['enchant_grade_rules.json','enchant_grade_exchange.json','enchant_grade_map_drops.json'])window.RO_WEB_DATA['data/'+f]=JSON.parse(fs.readFileSync(`${ROOT}/data/${f}`,'utf8'));
const itemIndex=JSON.parse(fs.readFileSync(`${ROOT}/data/items/item_index.json`,'utf8'));
itemIndex['900001']={id:900001,name:'測試五級武器',type:'equipment',category:'weapon',dbType:'Weapon',weaponLevel:5,atk:100,matk:50};
window.getItemData=id=>itemIndex[String(Number(id))]||null;
window.player={zeny:20000000,inventory:[],equipment:{weapon:null},equipmentInstances:{},map:'ice_scale_hill_3x3_region_camera'};
window.currentMap={id:'ice_scale_hill_3x3_region_camera'};
window.addItem=(x,q=1)=>{let r=player.inventory.find(v=>v.id===x.id&&!v.instanceId);if(r)r.count+=q;else player.inventory.push({id:x.id,count:q,name:x.name});};
for(const fn of ['saveGame','recalculatePlayerStats','updatePlayerUI','updateInventoryUI','updateEquipmentUI','updateStatusUI','updateQuickSlotUI','addBattleLog','recordItemDrop','emitLootRewardLog'])window[fn]=()=>{};
window.RefineRuntime={refineBonusFor:()=>({bonus:100})};
vm.runInThisContext(fs.readFileSync(`${ROOT}/js/enchant_grade_runtime.js`,'utf8'));
const G=window.EnchantGradeRuntime;let passed=0;
function ok(v,msg){if(!v)throw new Error(msg);passed++;console.log('PASS',msg);}
ok(G.rules().groups.Weapon.levels['5'].grades.None.chances['9']===1000,'RA Lv5 weapon None→D +9 chance = 10%');
ok(G.rules().groups.Armor.levels['2'].grades.B.options[1].amount===10,'RA Armor B→A safe option uses 10 Etel Amber');
ok(G.exchanges().recipes.length===6,'six exact RA material exchange recipes');
player.inventory=[{id:900001,itemId:900001,count:1,refine:9,enchantGrade:0,instanceId:'w1'},{id:1000325,count:20},{id:1000337,count:100}];
G.state.selected={key:'inventory:w1',instanceId:'w1'};G.state.optionIndex=0;G.state.catalystSteps=10;
let result=G.attemptSelectedGrade({forceSuccess:true});let w=player.inventory.find(x=>x.instanceId==='w1');
ok(result.success&&w.enchantGrade===1&&w.refine===0,'success raises grade and resets refine to +0');
w.refine=10;player.inventory.push({id:1000326,count:10});G.state.optionIndex=1;G.state.catalystSteps=0;result=G.attemptSelectedGrade({forceFail:true});
ok(result.ok&&!result.success&&player.inventory.some(x=>x.instanceId==='w1'),'safe failure preserves the same equipment instance');
player.inventory.push({id:900001,itemId:900001,count:1,refine:9,enchantGrade:0,instanceId:'w2'},{id:1000325,count:5});G.state.selected={key:'inventory:w2',instanceId:'w2'};G.state.optionIndex=0;result=G.attemptSelectedGrade({forceFail:true});
ok(result.ok&&!player.inventory.some(x=>x.instanceId==='w2'),'high-risk failure destroys equipment');
player.inventory.push({id:1000322,count:10});const beforeZ=player.zeny;result=G.exchange(0,2);
ok(result.ok&&player.inventory.some(x=>x.id===1000323&&x.count>=2)&&player.zeny===beforeZ-200000,'Etel Dust synthesis consumes materials and Zeny');
Math.random=()=>0;const beforeDust=G.inventoryCount(1000322);const awards=G.rollMapBonusDrops({id:21525,drops:[{itemId:1000322}]});
ok(!awards.some(x=>x.itemId===1000322)&&G.inventoryCount(1000322)===beforeDust,'bonus drop skips material already present in original drop table');
console.log(JSON.stringify({version:'0.9.82GK',passed}));
