const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');const load=r=>JSON.parse(fs.readFileSync(path.join(root,r),'utf8'));const assert=(v,m)=>{if(!v)throw new Error(m)};
const core=load('data/skills/skills_core_1.json'),rt=load('data/skill_runtime/runtime_core_1_v1.json'),gen=load('data/skill_runtime/runtime_generated_all.json'),pend=load('data/skill_runtime/runtime_pending_review.json');
const ids=[125,147,394,499];assert(rt.version==='0.9.82CO','runtime version');assert(gen.summary.officialRuntime===802,'official count');assert(gen.summary.pending===337,'pending count');
ids.forEach(id=>{assert(rt.skills[String(id)]?.executionEnabled===true,`runtime ${id}`);assert(!pend.skills.some(x=>Number(x.skillId)===id),`pending ${id}`)});
assert(core.skills['125'].skillType==='passive'&&core.skills['147'].skillType==='passive','passive types');
// Passive aggregation and formula capture.
const monster={name:'動物目標',currentHp:999999,maxHp:999999,level:1,flee:0,def:0,mdef:0,race:'Brute',element:'Neutral',position:{x:32,y:0},runtimeState:{statuses:{}}};
const sandbox={console,window:{},document:{getElementById:()=>null,querySelector:()=>null,querySelectorAll:()=>[]},setInterval:()=>0,clearInterval:()=>{},setTimeout:()=>0,clearTimeout:()=>{},Date,Math:Object.create(Math)};sandbox.window=sandbox;sandbox.Math.random=()=>0;
sandbox.player={baseLevel:200,jobLevel:70,maxHp:10000,hp:10000,maxSp:9999,sp:9999,stats:{str:100,agi:1,vit:1,int:1,dex:120,luk:1},learnedSkills:{'125':1,'147':1,'394':10,'499':1},activeBuffs:{},equipment:{weapon:1},position:{x:0,y:0},jobKey:'bard'};
sandbox.currentMonster=monster;sandbox.activeMonsters=[monster];sandbox.mapMonsters=[monster];sandbox.skillsData={skillIndex:{},runtimeProfiles:rt.skills};ids.forEach(id=>sandbox.skillsData.skillIndex[String(id)]={...core.skills[String(id)],runtimeProfile:rt.skills[String(id)].runtimeProfile});
sandbox.getSkillLevel=id=>Number(sandbox.player.learnedSkills[String(id)]||0);sandbox.getSkillDataById=id=>sandbox.skillsData.skillIndex[String(id)]||null;sandbox.getCurrentJobSkills=()=>ids.map(id=>sandbox.skillsData.skillIndex[String(id)]);
sandbox.getItemData=()=>({dbSubType:'musical',weaponType:'musical',atk:100});sandbox.getEquippedWeaponTypeRuntime=()=> 'musical';sandbox.calculateDerivedPlayerStats=()=>({stats:sandbox.player.stats,atk:100,matk:50,matkMin:50,matkMax:50,hit:999,cri:0});sandbox.addBattleLog=()=>{};sandbox.updateMonsterUI=()=>{};sandbox.updatePlayerUI=()=>{};sandbox.saveGame=()=>{};sandbox.canAttackMonsterByRange=()=>true;sandbox.getSkillRangePx=()=>999;sandbox.RO_WEB_CELL_SIZE=32;sandbox.showDamageNumber=()=>{};sandbox.playMonsterHitAnimation=()=>{};sandbox.playROStudioPlayerMotion=()=>{};sandbox.stopAutoBattle=()=>{};sandbox.defeatMonster=()=>{};
let captured=[];sandbox.CombatDamagePipeline={resolvePhysicalSkill:(p,l,t,o)=>{captured.push(o.ratio);return {damage:o.ratio}},resolveMagicSkill:()=>({damage:0})};sandbox.HitResolver={resolve:()=>({hit:true})};sandbox.CriticalResolver={resolve:()=>({critical:false,multiplier:1})};sandbox.PerfectDodgeResolver={resolve:()=>({dodged:false})};sandbox.MultiHitResolver={normalize:(p,l)=>({damageHitCount:Number(p.damageHitCount||1),visualHitCount:Number(p.visualHitCount||1),statusProcMode:'once'}),split:d=>[d]};sandbox.TargetingResolver={collect:(origin,cands,o)=>[monster]};sandbox.AreaShapeResolver={inRange:()=>true};
vm.createContext(sandbox);for(const f of ['js/combat_mechanics_runtime.js','js/skill_engine.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),sandbox);
const passive=sandbox.getPassiveSkillBonusTotals();assert(passive.longPhysicalDamageRate===6,`passive ranged ${passive.longPhysicalDamageRate}`);
assert(sandbox.castAttackSkill(sandbox.skillsData.skillIndex['394'],10,{skipHitCheck:true,silent:true}),'arrow vulcan');assert(captured.pop()===3000,'arrow vulcan ratio');
sandbox.getEquippedWeaponTypeRuntime=()=> 'bow';assert(sandbox.castAttackSkill(sandbox.skillsData.skillIndex['499'],1,{skipHitCheck:true,silent:true}),'beast strafing');assert(captured.pop()===850,'beast ratio');
monster.race='Demon';const before=monster.currentHp;assert(sandbox.castAttackSkill(sandbox.skillsData.skillIndex['499'],1,{skipHitCheck:true,silent:true}),'beast invalid cast returns');assert(monster.currentHp===before,'beast race restriction');
// Actual ranged passive in damage pipeline.
const pctx={window:{},console,Math:Object.create(Math)};pctx.window=pctx;pctx.Math.random=()=>0;pctx.player={baseLevel:100,stats:{str:1,dex:1,luk:1},equipment:{weapon:1},attackElement:'Neutral'};pctx.currentMonster={race:'Brute',size:'Medium',element:'Neutral',elementLevel:1,def:0,mdef:0,currentHp:10000};pctx.getItemData=()=>({atk:100,weaponLevel:1,weaponType:'bow',dbSubType:'bow'});pctx.calculateDerivedPlayerStats=()=>({atk:200,matk:1,stats:pctx.player.stats,cri:0});pctx.getTrainingBonusTotals=()=>({});pctx.getActiveBuffBonusTotals=()=>({});pctx.getPassiveTargetDamageBonus=()=>0;pctx.applyROCombatDamageModifiers=n=>n;let ranged=0;pctx.getPassiveSkillBonusTotals=()=>({longPhysicalDamageRate:ranged});vm.createContext(pctx);vm.runInContext(fs.readFileSync(path.join(root,'js/ra_renewal_damage_pipeline.js'),'utf8'),pctx);const base=pctx.RARenewalDamagePipeline.resolveNormalAttack(pctx.currentMonster,{criticalResult:{critical:false,multiplier:1}}).damage;ranged=6;const boosted=pctx.RARenewalDamagePipeline.resolveNormalAttack(pctx.currentMonster,{criticalResult:{critical:false,multiplier:1}}).damage;assert(boosted===Math.floor(base*1.06),`ranged pipeline ${base}->${boosted}`);
console.log(JSON.stringify({result:'PASS',version:'0.9.82CO',official:802,pending:337,passiveRanged:6,arrowVulcanRatio:3000,beastStrafingRatio:850,normalDamage:{base,boosted}},null,2));
