const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..'),j=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const core=j('data/skills/skills_core_1.json').skills,runtime=j('data/skill_runtime/runtime_core_1_v1.json').skills;
const generated=j('data/skill_runtime/runtime_generated_all.json'),pending=j('data/skill_runtime/runtime_pending_review.json');
const ids=[2240,2241,2242,2243,2244,2245,2246];
for(const id of ids){assert.strictEqual(core[id].implementationStatus,'runtime_ready',`core ${id}`);assert(runtime[id]?.executionEnabled,`runtime ${id}`);assert(generated.skills[id]?.executionEnabled,`generated ${id}`);assert(!pending.skills.some(x=>Number(x.skillId)===id),`pending ${id}`);}
assert.strictEqual(generated.summary.officialRuntime, 754);assert.strictEqual(generated.summary.pending,385);
assert.deepStrictEqual(ids.map(id=>core[id].name),['召狼術','騎狼術','疾狼術','狼突擊','狼咬','狼牙','敏銳嗅覺']);
const ctx={window:null,console,Date,setTimeout:()=>0,clearTimeout:()=>{},setInterval:()=>0,clearInterval:()=>{},Math:Object.create(Math)};ctx.window=ctx;ctx.Math.random=()=>0;
ctx.skillsData={runtimeProfiles:runtime,skillIndex:core};
ctx.player={jobKey:'ranger',baseLevel:200,jobLevel:70,hp:10000,maxHp:10000,sp:10000,maxSp:10000,stats:{str:80,agi:120,vit:60,int:40,dex:120,luk:90},equipment:{weapon:1},learnedSkills:{2240:1,2241:3,2242:1,2243:5,2244:5,2245:10,2246:5},activeBuffs:{},position:{x:0,y:0},walkSpeed:150};
const hidden={name:'Hidden',currentHp:999999,maxHp:999999,element:'Neutral',race:'Formless',size:'Medium',position:{x:64,y:0},stats:{agi:80,luk:0},hardDef:0,softDef:0,runtimeState:{statuses:{hiding:{name:'Hiding',effects:{}}}},hidden:true,visible:false};
ctx.currentMonster=hidden;ctx.activeMonsters=[hidden];
ctx.getSkillLevel=id=>Number(ctx.player.learnedSkills[id]||0);ctx.getSkillDataById=id=>core[String(id)]||null;ctx.getCurrentJobSkills=()=>ids.map(id=>core[String(id)]);ctx.getExtraSkillSkillList=()=>[];
ctx.calculateDerivedPlayerStats=()=>({stats:{str:80,agi:120,vit:60,int:40,dex:120,luk:90},atk:500,hit:300,cri:10,walkSpeed:150,pAtk:0});ctx.getTrainingBonusTotals=()=>({});ctx.getItemData=()=>({weaponType:'bow',dbSubType:'bow',atk:200,range:5});ctx.getEquippedWeaponTypeRuntime=()=> 'bow';
ctx.RO_WEB_CELL_SIZE=32;ctx.getCombatGroundCandidates=()=>ctx.activeMonsters;ctx.canAttackMonsterByRange=()=>true;ctx.getSkillRangePx=()=>9999;ctx.movePlayerTowardMonster=()=>{};
ctx.addBattleLog=()=>{};ctx.showDamageNumber=()=>{};ctx.playMonsterHitAnimation=()=>{};ctx.updateMonsterUI=()=>{};ctx.updatePlayerUI=()=>{};ctx.saveGame=()=>{};ctx.recalculatePlayerStats=()=>{};ctx.defeatMonster=()=>{};ctx.renderPositionSprites=()=>{};
for(const file of ['js/combat_mechanics_runtime.js','js/combat_formula_runtime.js','js/ra_renewal_damage_pipeline.js','js/combat_damage_pipeline.js','js/position_engine.js','js/skill_engine.js'])vm.runInNewContext(fs.readFileSync(path.join(root,file),'utf8'),ctx,{filename:file});
const passive=ctx.getPassiveSkillBonusTotals();assert.strictEqual(passive.wargDamageFlat,600);assert.strictEqual(passive.wargBiteChanceBonus,40);assert.strictEqual(passive.wargBiteDurationBonusMs,5000);
ctx.player.hasFalcon=true;assert(ctx.castWargToggleSkill(core['2240'],1));assert(ctx.isWargActiveRuntime());assert(!ctx.isFalconActiveRuntime());
assert(ctx.castWargRideToggleSkill(core['2241'],3));assert(ctx.isWargRidingRuntime());assert.strictEqual(ctx.getActiveBuffBonusTotals().moveSpeedRate,30);
const dash=ctx.calculateSkillAttackDamage(core['2242'],1,hidden,{skipHitCheck:true});assert(dash>600);assert.strictEqual(ctx.lastRADamageTrace.ratio,300);
const strike=ctx.calculateSkillAttackDamage(core['2243'],5,hidden,{skipHitCheck:true});assert(strike>dash);assert.strictEqual(ctx.lastRADamageTrace.ratio,1000);
const beforeAuto=hidden.currentHp;assert(ctx.tryWargAutoStrikeOnNormal(hidden));assert.strictEqual(beforeAuto-hidden.currentHp,strike);
assert(ctx.castWargRideToggleSkill(core['2241'],3));assert(!ctx.isWargRidingRuntime());
const bite=ctx.calculateSkillAttackDamage(core['2244'],5,hidden,{skipHitCheck:true});assert(bite>strike);assert.strictEqual(ctx.lastRADamageTrace.ratio,1500);assert(ctx.applyAttackRuntimeStatus(runtime['2244'].runtimeProfile,5,hidden));assert(ctx.StatusManager.has(hidden,'warg_bite'));
const trapId=ctx.GroundEffectManager.create({id:'warg_trap_test',x:64,y:0,shape:'circle',rangeCells:0,sourceSkillId:116,durationMs:10000,maxTicks:1});assert(trapId);
hidden.hidden=true;hidden.visible=false;hidden.runtimeState.statuses.hiding={name:'Hiding',effects:{}};const beforeKeen=hidden.currentHp;assert(ctx.castWargSensitiveKeenSkill(core['2246'],5));assert(hidden.currentHp<beforeKeen);assert(!hidden.hidden&&hidden.visible!==false);assert(!ctx.GroundEffectManager.effects.has(trapId));
assert(ctx.castWargToggleSkill(core['2240'],1));assert(!ctx.isWargActiveRuntime());assert(!ctx.isWargRidingRuntime());
console.log(JSON.stringify({result:'PASS',official:754,pending:385,wargDamageFlat:passive.wargDamageFlat,dash,strike,bite,sensitiveDamage:beforeKeen-hidden.currentHp},null,2));
