const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..');const load=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const core=load('data/skills/skills_core_1.json').skills,runtime=load('data/skill_runtime/runtime_core_1_v1.json').skills;
let now=100000;class FakeDate extends Date{static now(){return now}};const math=Object.create(Math);math.random=()=>0.99;
const shown=[],logs=[],defeated=[];const ctx={window:null,console,Date:FakeDate,Math:math,setTimeout:()=>0,clearTimeout:()=>{},setInterval:()=>0,clearInterval:()=>{}};ctx.window=ctx;ctx.RO_WEB_CELL_SIZE=36;
ctx.skillsData={runtimeProfiles:runtime,skillIndex:core};ctx.player={jobKey:'sniper',baseLevel:73,jobLevel:48,hp:10000,maxHp:10000,sp:10000,maxSp:10000,stats:{str:1,agi:90,vit:1,int:1,dex:120,luk:1},equipment:{weapon:1},learnedSkills:{382:5},activeBuffs:{},position:{x:0,y:0}};
const m=(name,x,y,hp=100000)=>({name,currentHp:hp,maxHp:Math.max(hp,100000),element:'Neutral',race:'Formless',size:'Medium',position:{x,y},stats:{luk:0},hardDef:0,softDef:0,runtimeState:{},_worldTestEntity:true});
const primary=m('Primary',360,0,59),inline=m('Inline',180,40),off=m('Off',180,150),behind=m('Behind',-100,0),beyond=m('Beyond',500,0);const world=[primary,inline,off,behind,beyond];ctx.currentMonster=primary;
ctx.getCombatGroundCandidates=()=>world;ctx.getWorldMonsterTestEntities=()=>world;
ctx.getSkillLevel=id=>Number(ctx.player.learnedSkills[id]||0);ctx.getSkillDataById=id=>core[String(id)]||null;ctx.getCurrentJobSkills=()=>Object.values(core);ctx.getExtraSkillSkillList=()=>[];
ctx.calculateDerivedPlayerStats=()=>({stats:{...ctx.player.stats},atk:500,hit:999,cri:0,crate:0,pAtk:0});ctx.getTrainingBonusTotals=()=>({});ctx.getPassiveTargetDamageBonus=()=>0;ctx.getPassiveSkillBonusTotals=()=>({});ctx.getActiveBuffBonusTotals=()=>({});ctx.applyROCombatDamageModifiers=d=>d;
ctx.getItemData=()=>({weaponType:'bow',dbSubType:'Bow',atk:200,range:11});ctx.getEquippedWeaponTypeRuntime=()=> 'bow';ctx.canAttackMonsterByRange=()=>true;ctx.getSkillRangePx=()=>9999;
ctx.addBattleLog=t=>logs.push(String(t));ctx.showDamageNumber=(v,o)=>shown.push({v:Number(v),target:o?.target?.name});ctx.playMonsterHitAnimation=()=>{};ctx.updateMonsterUI=()=>{};ctx.updatePlayerUI=()=>{};ctx.saveGame=()=>{};ctx.recalculatePlayerStats=()=>{};ctx.showSlashEffect=()=>{};
ctx.playRuntimeSkillActionMotion=()=>{};ctx.playROStudioPlayerMotion=()=>{};ctx.consumeRuntimeCastAnimationHandoff=()=>false;ctx.StatusManager={onDamage:()=>{},normalize:s=>String(s)};ctx.recordMapMonsterDiscovery=()=>{};ctx.grantMonsterRewards=t=>defeated.push(t.name);ctx.onWorldMonsterDefeated=t=>{t._deathHandled=true};
for(const file of ['js/combat_mechanics_runtime.js','js/ra_renewal_damage_pipeline.js','js/combat_damage_pipeline.js','js/skill_engine.js'])vm.runInNewContext(fs.readFileSync(path.join(root,file),'utf8'),ctx,{filename:file});
const sharp=core['382'];const expected=ctx.calculateSkillAttackDamage(sharp,5,primary,{criticalResult:{critical:false,multiplier:1}});assert(expected>59);
assert.strictEqual(ctx.castAttackSkill(sharp,5,{skipHitCheck:true}),true);assert.strictEqual(primary.currentHp,0);assert(inline.currentHp<inline.maxHp);assert.strictEqual(off.currentHp,off.maxHp);assert.strictEqual(behind.currentHp,behind.maxHp);assert.strictEqual(beyond.currentHp,beyond.maxHp);
assert(logs.some(x=>x.includes('命中 2 個目標')));assert(logs.some(x=>x.includes(`共造成 ${expected*2} 點傷害`)));assert(shown.some(x=>x.target==='Primary'&&x.v===expected));assert(shown.some(x=>x.target==='Inline'&&x.v===expected));assert(defeated.includes('Inline')===false); // high HP secondary survives
console.log(JSON.stringify({version:'0.9.82EP',status:'PASS',calculatedDamage:expected,targets:2,source:'getCombatGroundCandidates'},null,2));
