const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'); const load=r=>JSON.parse(fs.readFileSync(path.join(root,r),'utf8'));
const core=load('data/skills/skills_core_1.json'),rt=load('data/skill_runtime/runtime_core_1_v1.json'),gen=load('data/skill_runtime/runtime_generated_all.json'),pend=load('data/skill_runtime/runtime_pending_review.json');
const ids=[2413,2414,2418,2419,2420,2422]; function assert(v,m){if(!v)throw new Error(m)}
assert(gen.summary.version==='0.9.82CJ','version');assert(gen.summary.officialRuntime===773,'official');assert(gen.summary.pending===366,'pending');ids.forEach(id=>{assert(rt.skills[String(id)]?.executionEnabled===true,`runtime ${id}`);assert(!pend.skills.some(x=>Number(x.skillId)===id),`pending ${id}`)});
let now=100000; class FakeDate extends Date{static now(){return now}}
const sandbox={console,window:{},document:{getElementById:()=>null,querySelector:()=>null,querySelectorAll:()=>[]},setInterval:()=>0,clearInterval:()=>{},setTimeout:(f)=>{f();return 0},clearTimeout:()=>{},Date:FakeDate,Math:Object.create(Math)};sandbox.window=sandbox;sandbox.Math.random=()=>0;
sandbox.player={jobLevel:70,baseLevel:200,maxHp:1000,hp:1000,maxSp:1000,sp:1000,stats:{str:1,agi:200,vit:1,int:120,dex:300,luk:1},learnedSkills:{'2412':10},activeBuffs:{},equipment:{weapon:1},position:{x:0,y:0},jobKey:'minstrel'};
function mon(name,x=0,y=0){return {name,currentHp:100000,maxHp:100000,level:50,stats:{int:20,luk:1},position:{x,y},runtimeState:{},def:0,mdef:0}}
sandbox.currentMonster=mon('目標');sandbox.activeMonsters=[sandbox.currentMonster,mon('旁邊',32,0)];
sandbox.skillsData={skillIndex:{},runtimeProfiles:rt.skills}; ids.forEach(id=>sandbox.skillsData.skillIndex[String(id)]={...core.skills[String(id)],runtimeProfile:rt.skills[String(id)].runtimeProfile});
sandbox.getSkillLevel=id=>Number(id)===2412?10:(Number(id)===2413?10:5);sandbox.getItemData=()=>({dbSubType:'instrument',weaponType:'instrument'});sandbox.getEquippedWeaponTypeRuntime=()=> 'instrument';sandbox.getSkillDataById=id=>sandbox.skillsData.skillIndex[String(id)];sandbox.calculateDerivedPlayerStats=()=>({stats:sandbox.player.stats,matkMin:100,matkMax:100,atk:100});sandbox.getPassiveSkillBonusTotals=()=>({});sandbox.getActiveBuffBonusTotals=()=>({});sandbox.getTrainingBonusTotals=()=>({});sandbox.getPassiveCombatModifierTotals=()=>({});sandbox.addBattleLog=()=>{};sandbox.updateMonsterUI=()=>{};sandbox.updatePlayerUI=()=>{};sandbox.saveGame=()=>{};sandbox.recalculatePlayerStats=()=>{};sandbox.paySkillCost=()=>{};sandbox.canAttackMonsterByRange=()=>true;sandbox.getSkillRangePx=()=>999;sandbox.playMonsterHitAnimation=()=>{};sandbox.showDamageNumber=()=>{};sandbox.renderPositionSprites=()=>{};sandbox.RO_WEB_CELL_SIZE=32;
vm.createContext(sandbox); for(const f of ['js/combat_mechanics_runtime.js','js/skill_engine.js']) vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),sandbox);
// Replace damage pipeline with deterministic ratios.
sandbox.CombatDamagePipeline={resolveMagicSkill:(p,l,t,o)=>({damage:o.ratio*o.hits}),resolvePhysicalSkill:(p,l,t,o)=>({damage:o.ratio}),resolveMiscSkill:(p,l,t,o)=>({damage:o.rawDamage})};
let d=sandbox.calculateSkillAttackDamage(sandbox.skillsData.skillIndex['2413'],10,sandbox.currentMonster);assert(d===3600,'metallic ratio');
d=sandbox.calculateSkillAttackDamage(sandbox.skillsData.skillIndex['2414'],5,sandbox.currentMonster);assert(d===4400,'reverberation ratio');
d=sandbox.calculateSkillAttackDamage(sandbox.skillsData.skillIndex['2418'],5,sandbox.currentMonster);assert(d===1204,'rainstorm instrument ratio');assert(rt.skills['2418'].runtimeProfile.duration===3400&&rt.skills['2418'].runtimeProfile.maxTicks===12,'rainstorm duration');sandbox.currentMonster.currentHp=100000;assert(sandbox.castGroundDamageSkill(sandbox.skillsData.skillIndex['2418'],5),'rainstorm cast');now+=100;sandbox.GroundEffectManager.update(now,sandbox.activeMonsters);assert(sandbox.currentMonster.currentHp===98796,'rainstorm tick');
// Deep sleep: chance guaranteed, target-adjusted duration, +50% damage, periodic heal, break on damage.
sandbox.currentMonster.currentHp=50000;const deep=sandbox.skillsData.skillIndex['2422'];assert(sandbox.castTimedStatusSkill(deep,5,{skipCost:true}),'deep cast');assert(sandbox.StatusManager.has(sandbox.currentMonster,'deep_sleep'),'deep status');const st=sandbox.currentMonster.runtimeState.statuses.deepsleep;assert(st.effects.damageTakenRate===50&&st.effects.periodicHealMaxHpPercent===3,'deep effects');assert(st.expiresAt-now===16500,'deep duration');sandbox.StatusManager.onDamage(sandbox.currentMonster,1);assert(!sandbox.StatusManager.has(sandbox.currentMonster,'deep_sleep'),'deep break');
// Siren prevents attack and breaks on damage.
const siren=sandbox.skillsData.skillIndex['2420'];assert(sandbox.castTimedStatusSkill(siren,5,{skipCost:true}),'siren cast');assert(sandbox.getMonsterRuntimeBonuses(sandbox.currentMonster).blocksPlayerAttacks===1,'siren block');sandbox.StatusManager.onDamage(sandbox.currentMonster,1);assert(!sandbox.StatusManager.has(sandbox.currentMonster,'voice_of_siren'),'siren break');
// Netherworld immediate ground trigger/root.
const poem=sandbox.skillsData.skillIndex['2419'];assert(sandbox.castGroundDebuffSkill(poem,5),'poem cast');now+=100;sandbox.GroundEffectManager.update(now,sandbox.activeMonsters);assert(sandbox.getMonsterRuntimeBonuses(sandbox.currentMonster).rooted===1,'netherworld root');
console.log('PASS 0.9.82CJ Minstrel/Wanderer offense and control core');
