const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..'),j=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const core=j('data/skills/skills_core_1.json').skills,runtime=j('data/skill_runtime/runtime_core_1_v1.json').skills;
assert.strictEqual(core['2241'].skillType,'passive');assert.strictEqual(core['2241'].runtimeHandler,'passive');
assert.deepStrictEqual(runtime['2241'].runtimeProfile.passiveBonuses.moveSpeedRate,[20,25,30]);
assert.strictEqual(runtime['2242'].runtimeProfile.requiresWarg,true);assert(!runtime['2242'].runtimeProfile.requiresWargRiding);
assert.strictEqual(runtime['6520'].runtimeProfile.requiresFalconOrWarg,true);
const ctx={window:null,console,Date,Math:Object.create(Math),setTimeout:()=>0,clearTimeout:()=>{},setInterval:()=>0,clearInterval:()=>{}};ctx.window=ctx;
ctx.skillsData={runtimeProfiles:runtime,skillIndex:core};ctx.player={jobKey:'ranger',baseLevel:200,stats:{str:1,agi:1,vit:1,int:1,dex:1,luk:1},equipment:{},learnedSkills:{2241:3},activeBuffs:{warg_rider_runtime:{id:2241,effects:{moveSpeedRate:30},expiresAt:Number.MAX_SAFE_INTEGER}},wargRiding:true,walkSpeed:150,position:{}};
ctx.getSkillLevel=id=>Number(ctx.player.learnedSkills[id]||0);ctx.getCurrentJobSkills=()=>[core['2241']];ctx.getExtraSkillSkillList=()=>[];ctx.getTrainingBonusTotals=()=>({});ctx.getItemData=()=>null;ctx.jobBasePoints={novice:{baseHp:{1:40},baseSp:{1:11}}};
for(const f of ['js/position_engine.js','js/skill_engine.js','js/status_system.js'])vm.runInNewContext(fs.readFileSync(path.join(root,f),'utf8'),ctx,{filename:f});
const p=ctx.getPassiveSkillBonusTotals();assert.strictEqual(p.moveSpeedRate,30);
ctx.normalizeActiveBuffs();assert.strictEqual(ctx.player.wargRiding,false);assert(!ctx.player.activeBuffs.warg_rider_runtime);
const d=ctx.calculateDerivedPlayerStats();assert.strictEqual(d.walkSpeed,115);
const px=ctx.raWalkSpeedToPixelsPerSecond(d.walkSpeed);assert(px>149&&px<151);
console.log(JSON.stringify({result:'PASS',moveSpeedRate:p.moveSpeedRate,walkSpeed:d.walkSpeed,pixelsPerSecond:px},null,2));
